### ISSUE TITLE
Google pay branding changed?

### ISSUE THREAD

**Issue by sandor111** [202-ecommerce/stripe_official#10]
I am trying to setup google pay and this button appears in test mode but it doesn't use the default google pay button branding because of which I am getting rejected from using google pay on my store :
![Screenshot_256](https://user-images.githubusercontent.com/17690323/80870866-603a0c00-8ca9-11ea-877a-ba991b547361.png)

**Comment by clotaire202** [comment]
Thank you for your issue.

I've contact Stripe Team for your problem. To enable Google Pay, you don't need a Google Pay Partner approval. It's not mandatory with Stripe to turn into production mode.

If you need more information about Stripe and Google Pay solution, please contact the Stripe official module support here https://addons.prestashop.com/contact-form.php?id_product=24922

Reagards
