### ISSUE TITLE
SOFORT / Klarna orders will not be created in the shop but marked as paid in stripe backend - Module ver. 2.3.7 / PS ver. 1.7.8.0

### ISSUE THREAD

**Issue by icemansparks** [202-ecommerce/stripe_official#100]
Since beginning of october we have problems with SOFORT Payments / Klarna Payments in our shop (PS version 1.7.7.8 and lastly 1.7.8.0).
The payment gets processed in stripe successfully but there is never an order created in prestashop.
We have credit card payments with the stripe module available as well and they don't create such a problem in comparison.

Payment details -> Description is also empty - compared to earlier module versions there was always (and also is for CC payments) the shop name and the shop order reference number in it. 

Stripe payment activity protocol doesn't show any errors though.

Prestashop Error Log says: PaymentModule::validateOrder - Order Status cannot be loaded

**Comment by clotairer** [comment]
Hi @icemansparks 

We published last week the version 2.4.0 that close your issue. Could you please install this version ?

If you need help from our technical team, please contact our support on this form
https://addons.prestashop.com/en/contact-us?id_product=24922

**Comment by clotairer** [comment]
Hi @icemansparks 

Here https://github.com/202-ecommerce/stripe_official/issues/104#issuecomment-991938641 @csingewald reported the same issue.

We fix your bug with SoFort on release [2.4.1](https://github.com/202-ecommerce/stripe_official/releases/tag/2.4.1)

Thank you.

**Comment by icemansparks** [comment]
@clotairer the issue is by far not fixed with version 2.4.1 - its different though.

We now get 
"description": "Product Purchase",

the payment seems to be handled by stripe, but there again is no order being created in the shop after the payment was done.
Customers are missing their shop confirmation mails as well and we don't even get information that there was an order at all. just seeing the payment in stripe, still with no order reference from prestashop.

I urge you to have a look at this again, this is really killing customer trust.

**Comment by clotairer** [comment]
Thank you for you feedback. I reopen this issue. Of course we are determined to fix this bug.
Can we have a look an a testing environment to reproduce the behaviour ?

**Comment by mariomaurer** [comment]
It looks like no shopping cart ID is passed with the call to Stripe. When Stripe reports back to the shop, an error "no shopping cart ID found" occurs.

**Comment by clotairer** [comment]
Ok thank you for the precision.

**Comment by icemansparks** [comment]
@clotairer we deinstalled the module after your last comment and installed it again - apart form the issue that we just discussed in #113 we had no further problems with the Klarna / SOFORT Payments so far.

**Comment by clotairer** [comment]
hi @icemansparks 

My team found a fix on 2.4.1-RC1 but I asked to [revert on 2.4.1-RC2](https://github.com/202-ecommerce/stripe_official/commit/006fc5d3eb980cd0b218236aa9c4f49ce3be7532) because I found the upgrade based on name and color of the state not enough strong and very risky...
I'm open to discuss about the risk with you and your experience. Perhaps we can add this fix.

**Comment by icemansparks** [comment]
@clotairer i had a look at the tables as well, checking if the status does exist just by name (which is also in the translation table and can be changed by the user) and Color seems to be very risky.
As I found out before, checking by Staus ID also doesn’t seem to be a great solution since the Staus IDs can vary a lot (if the owner created more statuses by themselves already for example)

the only other idea I can come up with right now, would be to just be sure and create a new status that will be used from there on?

**Comment by clotairer** [comment]
We thought also to create a wizard in the module to check and fix (and create a status only if necessary) manually all hidden configuration and status.
Thank you for your precious input.

**Comment by icemansparks** [comment]
Having a wizard will give reassurance to all shop owners, that everything is alright - I quite like the idea 👍

**Comment by clotairer** [comment]
Wizard is avalable here :
https://github.com/202-ecommerce/stripe_official/issues/115#issuecomment-1088555510

We just publish as pre-release [Stripe_Official 2.4.4](https://github.com/202-ecommerce/stripe_official/releases/tag/2.4.4) that sould fix
