### ISSUE TITLE
Update from 2.3.1 to 2.4.1

### ISSUE THREAD

**Issue by darkstudio** [202-ecommerce/stripe_official#109]
Hi,

We had a problem with generating the cart after payment (it happened several times in several months), we had reported a problem and support told us that it was fixed. we no longer had confidence and we had not updated but after the problem of capture today, we are told that after more than 9 months between the reporting of the bug on 2.3.1 and now, 202commerce would have corrected his module ERROR !! we have updated to 2.4.1, no longer possible to pay anything: An unexpected problem has occurred. Please contact the support: Stripe official (SCA-ready) Module - PrestaShop Addons

It really is a shame for a payment system. We are forced to revert to version 2.3.1 ... ONCE AGAIN (this is the 4th time.

**Comment by clotairer** [comment]
Hi @darkstudio 

2.4.2 is not in addons store and this release is testing by our QA ingineer.
i’ll try to find your support tickets on addons store. I’ll contact you to understand what’s happend with your website.

**Comment by darkstudio** [comment]
> Hi @darkstudio 
> 
> 2.4.2 is not in addons store and this release is testing by our QA ingineer.
> i’ll try to find your support tickets on addons store. I’ll contact you to understand what’s happend with your website.

Sorry, its 2.4.1, i have edited the post.

**Comment by clotairer** [comment]
I look for your threads on PrestaShop Addons Support tools but all exchanges are anonymous and I don't find any message from @darkstudio Could you please supply me the date of your last exchange with us or update your ticket by mention me "@clotairer" ?

Thank you.

**Comment by clotairer** [comment]
@darkstudio

Whithout error, I've not received a message on addons support 
https://addons.prestashop.com/en/contact-us?id_product=24922 (with @clotairer and github issue 109) to understand what's happend in your case.

We cannot fix your bug if I have no more explanation and no case to reproduce. 
I'll give you to short cut the customer support level 1 to help you kickly. As you want...

**Comment by clotairer** [comment]
Version 2.4.2 is release.
Without contact with you we cannot reproduce your issue and verify if your upgrade will be successful with 2.4.2...
