### ISSUE TITLE
Payment details / Description missing

### ISSUE THREAD

**Issue by viglu** [202-ecommerce/stripe_official#11]
Hi,

It should be nice if you could will the payment detail, description field with something like "{shopname} Order {order_id}
It would be easier for accounting department  to match payment and order.

Regards,
Luc

**Comment by clotaire202** [comment]
Thank you for your issue.

Could you please confirm you would like to show :

**Comment by viglu** [comment]
Yes I confirm.

**Comment by clotaire202** [comment]
OK we will add your request on the product backlog. The next realese 2.1.0 is already freeze but you demand looks interesting.

**Comment by jhoarau** [comment]
This issue has been published in the release 2.1.1 and this version of the module is available on addons.
