### ISSUE TITLE
Stripe SEPA payments not changing to Paid in orders page backend but show as PAID in Stripe interface

### ISSUE THREAD

**Issue by Benoit1980** [202-ecommerce/stripe_official#114]
Hello,

I have prestashop 1.7.8.2 and downloaded the stripe module 2.4.1.

When doing a test purchase with this card number(from stripe test accounts):

FR1420041010050500013M02606  
(The PaymentIntent status transitions from processing to succeeded.)

The payment is set to "succeeded" in the stripe back end but in the shop, it still shows up as :
"Waiting for Sepa Payment"

Any idea why please?

Thank you.

**Comment by clotairer** [comment]
Let me know, FR1420041010050500013M02606 is a sepa number used for bank wire. If you pay with a this payement method Stripe do not have the response of the bank to confirm the payment. So, the module create the order in a temporary state awaiting for payment. After several days, Stripe send the confirmation to the PrestaShop module that the payment is completed.

**Comment by Benoit1980** [comment]
Thank you so much for your response. 
I am a bit confused, I got the card from the Stripe testing page:

![sepa](https://user-images.githubusercontent.com/6231274/152973087-8388a99c-86de-470a-9bd7-75cb240533fc.jpeg)

So there is no way to simulate a SEPA transfer via a fake bank account? To test the hooks?
Do I need to do a real purchase instead?


Thanks

**Comment by Benoit1980** [comment]
Merci Pierre-Alain :-)

Tonight I will do some testing and see if it works, I will post back here to keep you updated.

Thanks again for the fast reply!

**Comment by Benoit1980** [comment]
Just to let you know I have downloaded the 2.4.2 version, passed a purchase with the SEPA ACCOUNT:
FR1420041010050500013M02606   which should transition the order to "succeeded", unfortunately, I am still seeing this:

![sepa](https://user-images.githubusercontent.com/6231274/153052815-c21847da-362a-49b0-91c1-634d01e731fd.jpeg)


Thanks,

Benoit

**Comment by pavillemagne202** [comment]
Thank you Benoit for your feedback.

Our developper is looking at this issue. 

Pierre-Alain

**Comment by Benoit1980** [comment]
Hi Pierre Alain, any good news on the issue, please?

Thank you.

**Comment by pavillemagne202** [comment]
Hi Benoit,
We cannot reproduce the issue on our environment.
To proceed to the solution of your problem, we will need access to your shop back office and we may also need FTP server access. 
Can you please contact our support https://addons.prestashop.com/en/contact-us?id_product=24922 and provide :

**1 - Shop back office access**
* Back office URL, example : http://www.yourshop.com/admin
* Username and password.
We recommend to create a temporary account, and delete this account once this ticket is closed.
If you prefer to provide us with a limited access, keep in mind we need access to the following headings : Catalog, Orders, Shipping and modules.
Please activate the consultation of the logs as in the image: http://prntscr.com/1j0xqa6

**2 - FTP access**
* Server host (and port), example : myshop.com port 21,
* Protocole : FTP / SFTP, etc...
* Username and password.

If you prefer to provide us with a limited access, keep in mind we need access to the module file
We recommend to create a temporary account, and delete this account once this ticket is closed.
We understand how sensible this information is, but we cannot solve your issue without such access.

To help us resolve your problem quickly, we ask you to:
- update Stripe to the latest version available
- add the TEST keys in the module configuration

Please also indicate that Pierre-Alain sent you to the support and that you need level 2 support for this issue.

Thanks in advance !

Pierre-Alain - 202 ecommerce

**Comment by Benoit1980** [comment]
Hi Pierre Alain,

Very much appreciated!
I have sent the request to your support with the above explanation.

Thanks and good luck!

Benoit

**Comment by Afayadas** [comment]
Hello Benoit, 

I looked at the problem you had with the module.

I identified the problem which comes from the verification of the payment module used during the order.
You can see the condition in ValidationOrderActions file code at line 724. If stripe_official isn't the module name use by the order, we stop webhook processing.

https://github.com/202-ecommerce/stripe_official/blob/develop/classes/actions/ValidationOrderActions.php#:~:text=if%20(%24order%2D%3Emodule%20!%3D%20%27stripe_official%27)%20%7B

In your case, I noticed that there are Prestashop table duplicates in database. Normally, the column "module" in "ps_orders" table is of varchar(255) type but in your database it is of varchar(9).
If you fix this detail, SEPA debit payment will be operational.

Do not hesitate to contact us on github if you encounter any other problem.

Alexandre - 202 ecommerce

**Comment by Benoit1980** [comment]
Thank you so much!
We will check it out in detail tomorrow.
I cannot work out why would the varchar had changed to 9. I need to speak to the other dev on the job.

Thanks again, much appreciated!

Benoit
