### ISSUE TITLE
Webhook URL not supporting multi-shop - stripe module v2.4.1 - prestashop v1.7.8.2

### ISSUE THREAD

**Issue by icemansparks** [202-ecommerce/stripe_official#115]
We created a second shop-front with the multi-shop functionality of prestashop.
After receiving the first orders in the second store-front, we realised, that the order payment status is not updated for those orders, even though the payment was already finished in stripe.

When visiting the stripe module settings, and selecting the second shop ("business"), the module did show a webhook url error (because the webhook url is referring to the original shop-front ("shop").
Trying to save the settings (as mentioned in the message) fixes the problem for this shop front, but the same problem will then occur on the original one.

It seems as if the webhook url is not saved individually for each shop front but only once, leading to errors with multiple shop-fronts.
![SCR-20220210-cqt](https://user-images.githubusercontent.com/11578975/153365872-31a277fa-35b0-4104-88e3-229a3b764625.png)

**Comment by clotairer** [comment]
Could you confirm me your module are in 2.4.2 ?

**Comment by icemansparks** [comment]
we updated the module to version 2.4.2 this morning - the error still persists when switching from one shop front to another (by using the shop-front selector in the upper right corner).

When selecting the "business" shop front while the error is shown and saving the settings, the error is not shown any more.
Switching back to "shop" (default) shop-front, we now have the error the other way around :) 

so yes, still happening with module version 2.4.2

I have to add, that i did not try to reinstall the module yet (because of business hours).

**Comment by clotairer** [comment]
We reproduce a bug when the new shop has a language different than the default language in the context all shop during the setup of the module.
We look for a workarround if we can fix it for you before the next release.

**Comment by clotairer** [comment]
Here a workarround : 
Il faudrait qu'il regarde la variables de configuration STRIPE_WEBHOOK_SIGNATURE dans la table ps_configuration. Si les colonnes id_shop_group et id_shop sont vides alors il va falloir supprimer celle-ci avant de réenregistrer la configuration.
D'ailleurs, il peut retrouver rapidement les variables de notre module avec la requête :
SELECT * FROM ps_configuration WHERE name LIKE '%STRIPE%';

**Comment by clotairer** [comment]
Here a workarround : 
Can you check if STRIPE_WEBHOOK_SIGNATURE on ps_configuration: if id_shop_group and id_shop are empty, you need to remove it and register the configurations on the backoffice of the module for each shop ? This configuration sould be configure for each shop with a specific configuration.

If the module is well configured, you can load this request SELECT * FROM ps_configuration WHERE name LIKE '%STRIPE%'; and check that none of configurations have null value for id_shop_group and id_shop.

**Comment by icemansparks** [comment]
@clotairer using the sql statement above i found that most of the values are actually NULL, only the ones where i changed the settings on this morning have values for id_shop_group and id_shop.

![SCR-20220210-knq](https://user-images.githubusercontent.com/11578975/153422208-39d04b04-c476-440d-a775-4100800be865.png)

> you need to remove it and register the configurations on the backoffice of the module for each shop ?
Removing the lines in the database would be no problem, but how can i register the configurations again so that the values will be added?

**Comment by clotairer** [comment]
Perhaps you can update these NULL configuration to the shop_id 1 (and group 1) and duplicate for shop_id 2.
After that if you update the configuration in your backoffice in the context shop id 1, only configuration shop 1 are updated and same with shop id 2.

It's intresting case to us to understand. You installed Stripe on a monoshop and after you create a multishop and activate Stripe on the second shop ? Or you setup 2 shops and installed Stripe after on both shops ?

**Comment by icemansparks** [comment]
@clotairer got some more information coming up:
We started with one shop (multi shop option deactivated). Everything was set up and we also configured stripe as well as other modules.
After some months now, we decided to create a second shop front to sell to business customers as well instead of just end customers. We therefore activated the multi shop option (thinking, that the configuration from shop 1 would be copied over to shop 2 as well). 
Afterwards we deactivated SOFORT (while selecting the option "all shops" in the shop selection button in the top right corner) because of a problem that has been fixed by now.
after activating SOFORT again (while having only selected the shop with ID 1) we found out, that the values are not taken over to shop id 2 and activated sofort for shop id 2 as well.

So much for the background story :)

Back to the current problem:
I duplicated the entries of the previously shared image in the ps_configuration table and set the duplicated ones to id_shop_group=1 and id_shop=2.

I set "VALUE" of STRIPE_WEBHOOK_ID and STRIPE_WEBHOOK_SIGNATURE to NULL for id_shop=2.
After that, i reloaded the backoffice and opened up the stripe module settings page for id_shop=1 and clicked "save".
I then switched to settings page for id_shop=2 (where i saw the error message again) and clicked "save" as well.
Error is now gone on the id_shop=2 page, but again appears on the settings page of id_shop=1.

Now the error is gone - although i am not sure, if everything will work as expected.

We also created a 3rd shop-front in a separate shop_group today (for testing) and found out that the values for provate key and secret are not prefilled in this case.
After manually adding them, and clicking "save" in the 3rd shop front strip settings, the following values where created in the database (and also no "webhook error" was shown).

![Bildschirmfoto 2022-02-10 um 18 42 25](https://user-images.githubusercontent.com/11578975/153465529-62cc7461-2752-408a-8937-2cb87e00b0a3.jpg)

Still, a lot of the other config values for strip (like STRIPE_OS_SOFORT_WAITING) are still missing for the 3rd shop front.

**Comment by clotairer** [comment]
So, with this new shop on a new group you found new bugs, but we don't know if bugs come from the new shop or the new group or both...
Configuration are not generated properly. You need to fix it manually. We can help you but we need:
- your priority and an ETA. Shop 1 accept payment today ? what about shop 2 ? 
- if possible, an empty of customers, specific module, order, ... and private data on a functional database. With order state, country, ... and a few product help us to give you the right configuration and found a fix.

**Comment by clotairer** [comment]
We schedule to work on the « wizzard » to Check and fix configuration next week.

I’ll keep you aware.

**Comment by clotairer** [comment]
Hi @icemansparks,

You'll found in attached file a zip module [stripe_wizard.zip](https://github.com/202-ecommerce/stripe_official/files/8417295/stripe_wizard.zip) to manage check of configuration accros all available shops.

You can check 3 level of checks:
- Verify if hooks are plugged
- Verify if order states are correctly associated with right 
![image](https://user-images.githubusercontent.com/52157233/161738233-29c32bb3-b834-44dc-b6c8-ae479f8c55b3.png)
- Verify if stripe keys are registered

 Sorry for the delay of our response, I hope this module can help you to fix your issue.

**Comment by clotairer** [comment]
Thank you for your feed back.

**Comment by clotairer** [comment]
Hi @icemansparks 
Any updates ? is it works for now ?

**Comment by icemansparks** [comment]
@clotairer we have had multiple orders with SOFORT payment working after the changes while also using the newest version 2.4.4 of the module (on multiple shop-fronts as well). Thank you for all the effort!

**Comment by clotairer** [comment]
2.4.4 is a pre-release. If you found any trouble or regression. Do not hesitate to inform me.
