### ISSUE TITLE
Wrong capture_method for sofort orders since v2.4.2 - payment rejected

### ISSUE THREAD

**Issue by icemansparks** [202-ecommerce/stripe_official#118]
After updating to version 2.4.2 last week, SOFORT Payments get rejected in stripe with the following error - saying that the capture_method for sofort payments needs to be "automatic" rather than "manual":

`"message": "The following payment method types ["sofort"] can only be used with PaymentIntents that have capture_method=automatic. Please retry by creating a PaymentMethod with capture_method=automatic."
"type": "invalid_request_error"`

I could not find any option for this kind of value in the module settings though.

Seems like there were multiple changes on the following file regarding sofort payment as well: [controllers/front/webhook.php](https://github.com/202-ecommerce/stripe_official/pull/107/commits/e1ac260eb0246ba23a4dad6c4fa54d6f12e53aba#diff-730e211e4f16ecc60980dc6637ae8f468f8955e8f3dd171662714cdb42178072)

![SCR-20220214-c8o](https://user-images.githubusercontent.com/11578975/153822147-76fdcdbb-1271-4c60-868c-347d54a2162a.png)

**Comment by clotairer** [comment]
You right the condition [here](https://github.com/202-ecommerce/stripe_official/pull/107/commits/e1ac260eb0246ba23a4dad6c4fa54d6f12e53aba#diff-730e211e4f16ecc60980dc6637ae8f468f8955e8f3dd171662714cdb42178072R551) looks like not right.
In your case, your controller just need to be charged and go to the else case.

We changed the condition to fix a bug (An error appears when paying with Alipay, Bancontact, EPS, iDEAL and P24 after redirect from stripe test payment page when Authorize payment) and get a regression. (FPX, OXXO, Giropay, SOFORT was right according to our QA ingeneer before the commit), I suppose he test back only Alipay, ... and not those who worked. So, if you don't use Alipay, Bancontact, EPS, iDEAL and P24, you can put the older condition L551.

**Comment by icemansparks** [comment]
I would honestly rather not change payment related code by myself and instead wait for the fix in the module itself from you guys (since we're also using iDEAL, Giropay and Bancontact this would not bring us full closure on all problems anyway).

Meanwhile, we will deactivate SOFORT payment in the shop.

**Comment by clotairer** [comment]
OK, that's clear. We will do our best to found a quick fix.

**Comment by davidaames** [comment]
I have the same problem, what would i have to change on L551 exactly to make sofort work again?

**Comment by clotairer** [comment]
I don't know if your are at ease with code. It's better to send an message to our support :  https://addons.prestashop.com/en/contact-us?id_product=24922 and indicate that @clotairer sent you to the support and that you need level 2 support for issue #118.
