### ISSUE TITLE
Wrong postal code form field

### ISSUE THREAD

**Issue by Teddy-GFCOM** [202-ecommerce/stripe_official#134]
Hello,

I currently have a PrestaShop 1.7.8.2 with Stripe 2.4.2 installed and configured on it. The website use CloudFlare CDN.
My PrestaShop sell only virtual products.
PrestaShop is in French (default) and English.

A customer tried to make an order with a address in Canada. Everything worked fine in PrestaShop, except that Stripe Card Form asked for a Postal Code in french format `NNNNN` instead of a Canadian format, eg. `S4T 1T2`

The only fix I found was to disable the Postal Code in the form (not recomended)

**Comment by clotairer** [comment]
Hi @Teddy-GFCOM 

This part is totally manage by Stripe Elements which is the front end library of Stripe.
According to the stripe documentation : https://stripe.com/docs/js/element/postal_code_formatting postal code format depend of the credit cad number. Do you have make the test with a Canadian Credit Card ?

**Comment by Teddy-GFCOM** [comment]
Hi @clotairer 

Thank you.

After testing with a Canadian Credit Card (picked here https://stripe.com/docs/testing#international-cards) the forms works well, there is no issue.
