### ISSUE TITLE
Order Confirmed with uncorrect carrier and Total Paid different from Total Paid real

### ISSUE THREAD

**Issue by Uebix** [202-ecommerce/stripe_official#140]
With version 2.4.3 we have problems on orders. All orders hasn't the correct carrier. But the payment is correct.
So we have incongruity from the total paid and the total order in backoffice.

With the previous version 2.4.2 of the module the order was correct.

PrestaShop version 1.7.7.2

**Comment by clotairer** [comment]
Stripe module should have no impact on carrier set on orders. So it could be a conflict with an other module or a specific configuration.
