### ISSUE TITLE
Unexpected problem on credit card payment since version 2.3.1

### ISSUE THREAD

**Issue by darkstudio** [202-ecommerce/stripe_official#146]
Hi,
Prestashop 1.7.5.6
PHP 7.3
Stripe 2.3.1

I have already mention this bug bug i am always stuck since many month in version 2.3.1 of stripe module.
When we update on any version after 2.3.1 (i have just tried 2.4.3), we have a error message on last step.
To avoid make reccurent problem on the live website, we have clone the prestashop localy to make tests.
![bug_stripe](https://user-images.githubusercontent.com/6309663/166947054-8d518c96-27fb-406f-99e9-4355a908ed08.JPG)

Very annoying.

**Comment by darkstudio** [comment]
Additonnaly (for other people), when i use "bancontact", i have an other error message
![image](https://user-images.githubusercontent.com/6309663/166950029-e46481c4-1061-4d77-8b5c-418f531f2ddd.png)

**Comment by lmeyer1** [comment]
@clotairer
The error occurs here https://github.com/202-ecommerce/stripe_official/blob/5631793cf2e3645440ccd2494a0ca431f0615225/controllers/front/createIntent.php#L307.
That means that `$stripeEvent` cannot be saved.

**Comment by lmeyer1** [comment]
@clotairer @darkstudio The root problem is that the update scripts have not been run. (i.e. the table `ps_stripe_event` is missing.
Is there a way to rerun them ?

**Comment by clotairer** [comment]
The reset of the module sould install tables, and verify hooks.

**Comment by lmeyer1** [comment]
@clotairer Thanks. It worked. I had to review the configuration and save to regenerate the webhooks. No everything is OK.

**Comment by clotairer** [comment]
The remain problem is why do you have an Stripe without ps_stripe_event table ? Is there a problem during the last upgrade of the module ?

**Comment by clotairer** [comment]
So, @darkstudio perhaps you can try this and tell us if it's better.


> The reset of the module sould install tables, and verify hooks.
> 
> An other way is to add these line in the getContent() method and call the configuration page one time (and remove this after):
> 
> ```
>         $installer = new Stripe_officialClasslib\Install\ModuleInstaller($this);
>         $installer->install();
> ```

**Comment by darkstudio** [comment]
Ok error message gone but 2 new bug:

1) The payment is not captured even if the module is configured for and after payment confirmation, it will return to order history not the payment confirmation notice and the cart is not cleared.
![image](https://user-images.githubusercontent.com/6309663/167159764-71e67dfb-f7ce-42a9-b466-3737f162a471.png)
![image](https://user-images.githubusercontent.com/6309663/167159288-bcaee869-3931-44c3-8906-5f3d3d747146.png)

2) some payment method is not showed even is activated on module
![image](https://user-images.githubusercontent.com/6309663/167160380-2d7ddfdc-271e-4e2b-bd82-f02ebe778ec2.png)
![image](https://user-images.githubusercontent.com/6309663/167161003-ffc0b917-cd62-43a3-9cef-6e033bc652da.png)
![image](https://user-images.githubusercontent.com/6309663/167161098-9dd3953b-7fca-4e21-b090-9f79e26d2bbf.png)

**Comment by clotairer** [comment]
> The payment is not captured even if the module is configured for and after payment confirmation, it will return to order history not the payment confirmation notice and the cart is not cleared.
@Afayadas work on it this week. We will add a fix probably next week to publish the 2.4.4 final release

> some payment method is not showed even is activated on module

**Comment by clotairer** [comment]
@darkstudio The last issue you met should be fixed by this PR #161

**Comment by clotairer** [comment]
[2.4.5-RC1](https://github.com/202-ecommerce/stripe_official/releases/tag/2.4.5-RC1) released here and can be downloaded to test.

Thank you.
