### ISSUE TITLE
Problem with bancontact payment with 2.4.4

### ISSUE THREAD

**Issue by paul-jolimoi** [202-ecommerce/stripe_official#154]
Hello dear stripe_official maintainers,

We updated our stripe_official module from 2.4.2 to 2.4.4 and we saw that each payment made by Bancontact were failing.

When trying to reproduce the errors in test env, after submitting a success payment, we are redirected to the following error : 

![image](https://user-images.githubusercontent.com/78373471/173807118-2e1814f3-d317-410a-aefb-b799426bba83.png)

After investigating we found the problem cames from the changes that have been made in the condition here : 
https://github.com/202-ecommerce/stripe_official/blob/2.4.4/controllers/front/orderSuccess.php#L204

Before in 2.4.2 the condition was checking the `$eventType == 'succeeded'` and now in 2.4.4 it is checking `$eventType == 'charge.succeeded'`, so the handler actions are not correctly set, why has this changed?

Do we miss something that would make it receive an eventType `charge.succeeded`?

P.S : We use prestashop 1.7.8.3

**Comment by clotairer** [comment]
Hi, 

Thank you for reporting this.

I think you're right, we introduce a bug https://github.com/202-ecommerce/stripe_official/commit/51c18d95c6f73d437f456721b126b4c4e28b0cd2

In the controllers/front/orderSuccess.php > $eventType == 'succeeded'
In the controllers/front/webhook.php > $eventType == 'charge.succeeded'

Same variable name but value with for one and whithout  "charge." for the other...

Fixed in develop branch here https://github.com/202-ecommerce/stripe_official/commit/6ee73a4436bbba1951728bf7020979a849d570f3

It will be fixed in 2.4.5

Many thanks

**Comment by clotairer** [comment]
@ello10 
Stripe never returned "succeeded" but always returned "charge.succeeded". So for us your OR condition on $eventType in the webhookController is not mandatory.

**Comment by ello10** [comment]
We are talking about the status field, right ?? How about the trace below, which had the same symptoms (no order created in PS) :

En attente de réponse du webhook
Un webhook abonné à l'événement n'a pas encore répondu
Données de l'événement
{
"id": "removed",
"object": "charge",
"livemode": true,
"payment_intent": "removed",
"status": "succeeded",
"amount": 6390,
"amount_captured": 6390,
"amount_refunded": 0,
"application": null,
"application_fee": null,
"application_fee_amount": null,
"balance_transaction": "removed",
"billing_details": {
"address": {
"city": "removed",
"country": "BE",
"line1": "Rue De La removed, removed",
"line2": "",
"postal_code": "removed",
"state": null
},
"email": "nobody@gmail.com",
"name": "nobody",
"phone": null
},
"calculated_statement_descriptor": null,
"captured": true,
"created": 1655326596,
"currency": "eur",
"customer": null,
"description": "Product Purchase",
"destination": null,
"dispute": null,
"disputed": false,
"failure_balance_transaction": null,
"failure_code": null,
"failure_message": null,
"fraud_details": {
},
"invoice": null,
"metadata": {
"id_cart": "8450"
},
"on_behalf_of": null,
"order": null,
"outcome": {
"network_status": "approved_by_network",
"reason": null,
"risk_level": "not_assessed",
"seller_message": "Payment complete.",
"type": "authorized"
},
"paid": true,
"payment_method": "removed",
"payment_method_details": {
"bancontact": {
"bank_code": null,
"bank_name": null,
"bic": "removed",
"generated_sepa_debit": null,
"generated_sepa_debit_mandate": null,
"iban_last4": "6945",
"preferred_language": "en",
"verified_name": null
},
"type": "bancontact"
........

**Comment by clotairer** [comment]
@ello10 

You have two similar $eventType variable in:
- In the controllers/front/orderSuccess.php > $eventType == 'succeeded'
- In the controllers/front/webhook.php > $eventType == 'charge.succeeded'

In the webhookController (second item) sould always return $eventType prefixed by the name of the object in this case : charge followed by status.

The other controller orderSuccess, the JSON come from a callback of Stripe Elements JS and the `$eventType = $eventCharge->status;` As you mention in your json, status = "success". In this controller, the status is never prefixed by "charge."

I remember the right fix is commit here  https://github.com/202-ecommerce/stripe_official/commit/6ee73a4436bbba1951728bf7020979a849d570f3

Your suggestion work obviously but the OR condition is not mandatory to fix your issue.

I hope my answer is more clear. Do not hesitate if you want more explanation.

**Comment by clotairer** [comment]
[2.4.5-RC1](https://github.com/202-ecommerce/stripe_official/releases/tag/2.4.5-RC1) released here and can be downloaded to test.

Thank you.
