### ISSUE TITLE
Orders Uncaptured and no Order ID

### ISSUE THREAD

**Issue by BETTERTHANLIFE** [202-ecommerce/stripe_official#172]
Odd issue in the last week or so (2.4.3 originally)
Orders are coming through to prestashop look paid, but stripe account says "uncaptured" so I have to manually capture them
Also the strip description has changed it used to be "SiteName ORDERID" however it just now says "Product purchase"  Also for the created order (that looks like its paid) there is no stripe data, payment id, date, method etc

Also there is another entry for each order in stripe for incomplete, 

Event details for the product order state ""capture_method": "manual","

So I upgraded to the latest 2.4.4 and the issue is there still, so I have installed the 2.4.5 beta with the new capture option, turned it OFF so that it should capture the payment and its still the same.

**Comment by clotairer** [comment]
Hello,

Thank you for your clear explanation. 
I don't see exactly what's wrong.

We create a diagnostic module to verify some configuration:
1. Install this module [v1.0.0-prod-totsupport.zip](https://github.com/202-ecommerce/stripe_official/files/9467627/v1.0.0-prod-totsupport.zip)
2. Go to the configuration of this module and choose in the list the module Stripe.
3. Got to the Diagnostic tab
4. In the section "Orders states", you will have an array like that. Please verify all associations are fine.
![image](https://user-images.githubusercontent.com/52157233/187852378-f3f3cdb9-6750-40cc-ab5a-8cf03adcc80c.png)
If not, it tells what is not valid.
You can also verify, if tables of the module, hooks, and some others checks are OK.

Could you please share the results (screenshots) in case of failed diagnostics ?

If you found no errors, you need to contact in private our assistance to share logs and more information. Do not hesitate to write us to this [contact form](https://addons.prestashop.com/fr/contactez-nous?id_product=24922) in FR / EN or IT.

**Comment by BETTERTHANLIFE** [comment]
thanks for the assistance. I dont see order States in the list... 

I have.
Database integrity
Settings integrity
PrestaShop Overrides
Hooks
Hosting conditions
Logs
Export

**Comment by clotairer** [comment]
Do you have selected Stripe in the configuration tab ?
Is your all diagnostics OK ?

**Comment by BETTERTHANLIFE** [comment]
I got the configuration to display, I have everything valid and registered correctly apart from I have one hosting error (cache permissions, but that's a false reading as its is chmod correctly and working)  But there are overrides found on the following

classes/Hook.php
classes/Supplier.php
classes/Manufacturer.php
classes/controller/FrontController.php
classes/controller/Controller.php
classes/db/Db.php
classes/Media.php
classes/CMSCategory.php
classes/Product.php
classes/Link.php
classes/pdf/HTMLTemplateInvoice.php
classes/pdf/HTMLTemplateDeliverySlip.php
classes/pdf/HTMLTemplateOrderSlip.php
classes/Mail.php
classes/AddressFormat.php
classes/Category.php
classes/PaymentModule.php
classes/CartRule.php
classes/Cart.php
classes/Dispatcher.php
controllers/front/AddressController.php
controllers/front/ProductController.php
controllers/front/OrderController.php
controllers/front/IdentityController.php
controllers/front/AuthController.php
controllers/front/AddressesController.php
controllers/front/CartController.php
controllers/admin/AdminSuppliersController.php

**Comment by clotairer** [comment]
I don’t see easy error of configuration.

Last week I’ve a similary issue on a merchand. The module ps_crossellselling module purge the cache on validate order hook but throw an error during payment validation. After that, several payment was authorize but not capture.

You need to look in the ps_stripe_official_processlogger table if you see an error. Logs give you lot of informations.

Moreover, I see you have override of main class of PrestaShop not often overrided : Disparcher, DB, controller, frontcontroller, hook … other could not be linked to your issue in my mind.
Override of hook class often come from an RGPD module. You need to verify if Stripe is whitelist and all hooks are play. Lgcookielaw axeptio are OK, but becareful if you have rgpdpro. You need to check other overrides.

**Comment by BETTERTHANLIFE** [comment]
That sounds like my issue, on stripe theres several attempts before the uncaptured one

I shall take a look, Thinking back, the problems started a day or so after I installed Multi Accessories Pro Module, I have since uninstalled it.  But as you know uninstalling a module hardly removes much...

How do I manually remove the overrides left?

**Comment by clotairer** [comment]
You need to open each override files. On each function, the name of the module is in comment. You can remove each unuseful method. If no one remain, you can remove the file.

**Comment by BETTERTHANLIFE** [comment]
Thanks, removed a couple of left over functions from the above module (actually calls its self wkbundles)

Overrides now as follows, these are just SEO from ETS-SOFT, an invoice module and a one page checkout from PresTeamShop  These were on the site a long time and have been working with the stripe and paypal modules (side not sometimes customers are reporting "invalid response" on the paypal module)

classes/Hook.php
classes/Supplier.php
classes/Manufacturer.php
classes/controller/FrontController.php
classes/controller/Controller.php
classes/db/Db.php
classes/Media.php
classes/CMSCategory.php
classes/Product.php
classes/Link.php
classes/pdf/HTMLTemplateInvoice.php
classes/pdf/HTMLTemplateDeliverySlip.php
classes/pdf/HTMLTemplateOrderSlip.php
classes/Mail.php
classes/AddressFormat.php
classes/Category.php
classes/CartRule.php
classes/Cart.php
classes/Dispatcher.php
controllers/front/AddressController.php
controllers/front/ProductController.php
controllers/front/OrderController.php
controllers/front/IdentityController.php
controllers/front/AuthController.php
controllers/front/AddressesController.php
controllers/admin/AdminSuppliersController.php

**Comment by BETTERTHANLIFE** [comment]
This is how every payment via stripe comes through
https://ibb.co/YZqsr0j

**Comment by BETTERTHANLIFE** [comment]
To add, just been checking paypal payments and its not recording the transaction either...

using the 202  paypal addon
Heres the paypal addon log
Error code: 0;Short message: The elements in the shopping cart were changed. Please try to pay again.;
Error code: 0;Short message: Customer is not loaded object;

Clearly have something amiss, cannot work out what...

**Comment by BETTERTHANLIFE** [comment]
FOUND IT
classes/pdf/HTMLTemplateInvoice.php
classes/pdf/HTMLTemplateDeliverySlip.php
classes/pdf/HTMLTemplateOrderSlip.php

thought these were to do with my custom invoice addon, no... they were from the bundle products module. :)

**Comment by 202-ecommerce** [comment]
After years of hard work with Stripe connector for PrestaShop, 202 ecommerce will stop supporting Stripe module on January 9th 2023.
After this date, merchants will get [support directly](https://support.stripe.com/contact/email?topic=third_party_integrationshttps://support.stripe.com/contact/email?question=other&topic=third_party_integrations&subject=Prestashop%20Support%20Request&body=Include%20details%20of%20your%20Prestashop%20issue:%20)
