### ISSUE TITLE
Payment processing fails with "A processing error occurred." after upgrading to 2.1.0

### ISSUE THREAD

**Issue by jt3204** [202-ecommerce/stripe_official#18]
I've encountered an error affecting payments after upgrading to 2.1.0 on Prestashop 1.7.6.5

Payments were initially not being completed once the "Order with an obligation to pay" button was clicked and changed to "Processing...", as the process just hung at this stage.

In troubleshooting this issue, I have completely removed the module as well as renaming all the "ps_stripe..." tables in the database to try to start from scratch. After doing so, the first payment test using the test keys and card number work successfully. After this, all payments using the test or live keys fail with "A processing error occurred."

The relevant comments in the console are as follows:
Request URL: https://api.stripe.com/v1/payment_intents/pi_1GvgZJKxPxnnhXBEkiFQtqOc/confirm
Request Method: POST
Status Code: 400
"
{error: {code: "payment_intent_unexpected_state",…}}
error: {code: "payment_intent_unexpected_state",…}
code: "payment_intent_unexpected_state"
doc_url: "https://stripe.com/docs/error-codes/payment-intent-unexpected-state"
message: "You cannot confirm this PaymentIntent because it has already succeeded after being previously confirmed."
payment_intent: {id: "pi_1GvgZJKxPxnnhXBEkiFQtqOc", object: "payment_intent", amount: 740, canceled_at: null,…}
type: "invalid_request_error"
"
Then an event:
"
event: elements.confirm_payment_intent.server_error
event_count: 31
timestamp: 1592559663116
version: 8ce3d6c5
running_tests: false
frame_width: 1225
error-code: payment_intent_unexpected_state
error-doc_url: https://stripe.com/docs/error-codes/payment-intent-unexpected-state
error-message: You cannot confirm this PaymentIntent because it has already succeeded after being previously confirmed.
error-payment_intent-id: pi_1GvgZJKxPxnnhXBEkiFQtqOc
error-payment_intent-object: payment_intent
error-payment_intent-amount: 740
error-payment_intent-capture_method: automatic
error-payment_intent-client_secret: _*redacted*_
error-payment_intent-confirmation_method: automatic
error-payment_intent-created: <sanitized>
error-payment_intent-currency: gbp
error-payment_intent-livemode: false
error-payment_intent-payment_method_types: card
error-payment_intent-source: src_1GvgZvKxPxnnhXBEEJxO4n0w
error-payment_intent-status: succeeded
error-type: invalid_request_error
element: cardNumber
key: pk_test__*redacted*_
referrer: https://www._*redacted*_.com/store/order
betas: payment_intent_beta_3
stripe_js_id: 5a4247e6-8b45-4c67-8364-95284faac0e4
wrapper: unknown
es_module: false
"

Unsure of how to proceed from here as I can't see any issue with the setup of the module, and this issue only started after upgrading from the previous version of the module. Happy to collect more info as needed! Will roll back to previous version to keep the site live though.

**Comment by mribeiro202** [comment]
Hello jt3204,

We can help you on this subject but you have to contact the support service through this link :
https://addons.prestashop.com/en/payment-card-wallet/24922-stripe-official-sca-ready.html#seller

Have a nice day

**Comment by jt3204** [comment]
Thank you. Will do.
