### ISSUE TITLE
Orders with Uncaptured status

### ISSUE THREAD

**Issue by caovillanueva** [202-ecommerce/stripe_official#183]
I have a issue with a module using Presatshop 1.6
the stripe module (after update from 2.3.1 to v2.4.6 ) All new ordres are displaying with Uncaptured status.
![image](https://user-images.githubusercontent.com/1807788/192811883-037345b5-a802-4c06-b5d2-5bc770fd809f.png)

Also the Webhook is not working (it was working before).  In Events and logs section some activities says "Pending webhook response"

In Prestashop i got the status "En attente de capture Stripe" in orders section  (Its a French website).
When i change the status to "Livré" appears a error messag3
"Une erreur est survenue lors du changement d'état et/ou de l'envoi de l'e-mail au client.

![image](https://user-images.githubusercontent.com/1807788/192821464-fa442790-db83-48e4-93d9-672e59185827.png)

The prestashop store is 1.6.1.10 version

**Comment by caovillanueva** [comment]
Same issue when try with 2.4.4 version. for some reason the webhooks are not working to update status, this happen suddenly.

**Comment by clotairer** [comment]
Sorry for the delay. This notification was in spam.
There are some reason to have this issue. Could you please contact in private our assistance to share logs and more information by writing us to this [contact form](https://addons.prestashop.com/fr/contactez-nous?id_product=24922) in FR / EN or IT with reference github 183 (with the reference it's not necessary to repeat all your issue).

**Comment by gweit** [comment]
@clotairer as far as i can see the error you get might be caused by your SMTP-Settings, as it states Prestashop was not able to send the email to the customer.

**Comment by 202-ecommerce** [comment]
After years of hard work with Stripe connector for PrestaShop, 202 ecommerce will stop supporting Stripe module on January 9th 2023.
After this date, merchants will get [support directly](https://support.stripe.com/contact/email?topic=third_party_integrationshttps://support.stripe.com/contact/email?question=other&topic=third_party_integrations&subject=Prestashop%20Support%20Request&body=Include%20details%20of%20your%20Prestashop%20issue:%20)
