### ISSUE TITLE
Webhook dont get dispute

### ISSUE THREAD

**Issue by jyeste94** [202-ecommerce/stripe_official#186]
The module never change order status when stripe create dispute, because in the file webhook.php try get id_cart but stripe never send id_cart when create dispute.
 
![image](https://user-images.githubusercontent.com/73649267/200294331-e0d7b0bc-e50b-4780-a005-8f22bbd3187b.png)

![image](https://user-images.githubusercontent.com/73649267/200294361-9432ab0a-2985-430a-a2d2-72e8900af4d6.png)

**Comment by clotairer** [comment]
Thank you for your suggestion.

I confirm, Today the dispute is not manage by the webhook.

We will register this feature in the product back log and update this issue when/if the developpment will be schedule.

**Comment by 202-ecommerce** [comment]
After years of hard work with Stripe connector for PrestaShop, 202 ecommerce will stop supporting Stripe module on January 9th 2023.
After this date, merchants will get [support directly](https://support.stripe.com/contact/email?topic=third_party_integrationshttps://support.stripe.com/contact/email?question=other&topic=third_party_integrations&subject=Prestashop%20Support%20Request&body=Include%20details%20of%20your%20Prestashop%20issue:%20)
