### ISSUE TITLE
ps_stripe_official_processlogger become huge

### ISSUE THREAD

**Issue by williambamps** [202-ecommerce/stripe_official#195]
Hi guyz !
On my PS 1.7 the table ps_stripe_official_processlogger grow up around 500Mb each month, its look like the data stored are only info level log... Could it be possible to have a parameters to manager de log storage ? In production we want to log only errors, not info. 
Instead of that, could we clean this table every days ? 

Thanks !

**Comment by clotairer** [comment]
Hi,
You have an interface at this URL
https://domain.tld/adminXYZ/index.php?controller=AdminStripe_officialProcessLogger&configure=stripe_official&token=4a32d52617ea76770f7924254b14be47

**Comment by williambamps** [comment]
Hi,
Thanks for your quick reply
There is a way to access this page without know the URL ?
What do you mean by "log only level error." ? 
Indeed auto erasing don't work but I don't have any ideas why.. PS ring on Ubuntu, Apache, PHP 7.4 . Classic LAMP install

**Comment by clotairer** [comment]
>  There is a way to access this page without know the URL ?
Unfortunately not. A basic management "dissension"... But this view is very useful for our support team.

>  What do you mean by "log only level error." ?
You have 3 levels in the column "Level" in this array: success, info (verbose logs) and error.

>  Indeed auto erasing don't work but I don't have any ideas why.. PS ring on Ubuntu, Apache, PHP 7.4 . Classic LAMP install
Perhaps you can try to save the once the configuration form and see if new logs remove older logs (issue during the initialization of the configuration?). Note, if you have 500M... of logs, the first time can be long.

**Comment by HartLarsson** [comment]
> index.php?controller=AdminStripe_officialProcessLogger&configure=stripe_official

i've the same problem, the log is not deleting at all.
not working in 1.7.6.9 and 1.7.8.7 too

module version 2.4.6

Please add a button in stripe Backoffice to access the log page and parameters!
thanks

**Comment by clotairer** [comment]
A fix will be add in 2.5.1

**Comment by 202-ecommerce** [comment]
After years of hard work with Stripe connector for PrestaShop, 202 ecommerce will stop developping Stripe module on January 9th 2023.
After this date, merchants will get [support directly](https://support.stripe.com/contact/email?topic=third_party_integrationshttps://support.stripe.com/contact/email?question=other&topic=third_party_integrations&subject=Prestashop%20Support%20Request&body=Include%20details%20of%20your%20Prestashop%20issue:%20)
