### ISSUE TITLE
Webhook configuration cannot be found in PrestaShop, click on save button to fix issue.

### ISSUE THREAD

**Issue by M4ketech** [202-ecommerce/stripe_official#198]
Hello.

I have plugin version 2.5.0  with Prestashop 8.0.0.

When I go to plugin settings, I see warning "Webhook configuration cannot be found in PrestaShop, click on save button to fix issue. A new webhook will be created on Stripe, then saved in PrestaShop."

Also "Connect with Stripe" button will connect to Stripe and after I return to module settings, no settings are changed, keys will remain empty.

If I press "Save" I get:
"Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."

PHP version 8.0

**Comment by clotairer** [comment]
Thanks @M4ketech We will try to reproduce it.

**Comment by M4ketech** [comment]
Okay, I did do little bit troubleshooting. If you have no keys added on module configure page you will see:

"Oops! An Error Occurred
The server returned a "500 Internal Server Error".

If you input keys and then change some setting module gives notification "Settings updated successfully.".

**Comment by 202-ecommerce** [comment]
After years of hard work with Stripe connector for PrestaShop, 202 ecommerce will stop developping Stripe module on January 9th 2023.
After this date, merchants will get [support directly](https://support.stripe.com/contact/email?topic=third_party_integrationshttps://support.stripe.com/contact/email?question=other&topic=third_party_integrations&subject=Prestashop%20Support%20Request&body=Include%20details%20of%20your%20Prestashop%20issue:%20)
