### ISSUE TITLE
Upgrading from 2.4.6 to 2.5.0 - module cause an error and was deactivated

### ISSUE THREAD

**Issue by HartLarsson** [202-ecommerce/stripe_official#199]
During the upgrade the module get an error and was deactivated.
We need to reset it and reactivate manually to let it works.

**Comment by clotairer** [comment]
Hi,
what’s your PrestaShop version ?
Do you have logs on your PrestaShop ?

**Comment by HartLarsson** [comment]
PS 1.7.8.7 PHP7.2
i'm sorry i don't have the log (i tested in stage) but reactivating manually was without errors..
On production server we still with the previous version :)

**Comment by clotairer** [comment]
To optimize loading, we use in composer.json several optimization :
https://github.com/202-ecommerce/stripe_official/blob/1e241094e614b855a2f9526f69069148b4a31f1f/composer.json#L12-L16

In some case, when you upgrade Stripe Official, the request start with the previous autoload.php of vendor directory but during the upgrade need a new class in the new version the module. In this case, it may cause a fatal error and the upgrade is not apply properly.

In this case, you just need to click on upgrade.

I'll check if new classes are defined in the classmap in the 2.5.0 and not present in 2.4.6.

**Comment by 202-ecommerce** [comment]
After years of hard work with Stripe connector for PrestaShop, 202 ecommerce will stop developping Stripe module on January 9th 2023.
After this date, merchants will get [support directly](https://support.stripe.com/contact/email?topic=third_party_integrationshttps://support.stripe.com/contact/email?question=other&topic=third_party_integrations&subject=Prestashop%20Support%20Request&body=Include%20details%20of%20your%20Prestashop%20issue:%20)
