### ISSUE TITLE
No Logos shown

### ISSUE THREAD

**Issue by zzzZZZzzz9** [202-ecommerce/stripe_official#20]
No logos are shown in my 1.7.6.2 Prestashop for the Stripe payment methods. I checked in stripe_official.php and the line "->setLogo(Media::getMediaPath(_PS_MODULE_DIR_.$this->name.'/views/img/'.$cc_img))" was commented out. Removing the comment mark does not solve it as cc_img is not defined.

**Comment by mribeiro202** [comment]
Hi zzzZZZzzz9,

We can help you on this subject but you have to contact the support service through this link :
https://addons.prestashop.com/en/payment-card-wallet/24922-stripe-official-sca-ready.html#seller

Have a nice day
