### ISSUE TITLE
Stripe iDeal webhook error 400 charge.succeeded

### ISSUE THREAD

**Issue by trickbaze** [202-ecommerce/stripe_official#200]
Hi, when i buy a product on my PrestaShop site with Stripe iDeal and i click on Authorize test payment then i got an error in webhook logs, error 400 on charge.succeeded how can i fix this

**Comment by clotairer** [comment]
Hi,
There is an evolution in Stripe API and we commit a fix here: https://github.com/202-ecommerce/stripe_official/commit/0e85f5fe13982adcac679d8d7821ac3941dc4a26

It should be included on next release 2.5.1.

**Comment by 202-ecommerce** [comment]
After years of hard work with Stripe connector for PrestaShop, 202 ecommerce will stop developping Stripe module on January 9th 2023.
After this date, merchants will get [support directly](https://support.stripe.com/contact/email?topic=third_party_integrationshttps://support.stripe.com/contact/email?question=other&topic=third_party_integrations&subject=Prestashop%20Support%20Request&body=Include%20details%20of%20your%20Prestashop%20issue:%20)
