### ISSUE TITLE
Not possible to autosave credit card

### ISSUE THREAD

**Issue by crashncrow** [202-ecommerce/stripe_official#24]
Hi! 

I'm trying to use credit card autosave feature, but doesn't work.

The selector **input[data-module-name="stripe_official"]** not present, so param **card_form_payment** is always false

https://github.com/202-ecommerce/stripe_official/blob/b6238b9fe6f974f6f70acbcd30ef852d827d76a9/_dev/js/payments.js#L463

Where it's supposed to be?

Thanks!

**Comment by clotaire202** [comment]
Hi,

Thank you for your question. We will verify that.

The version 2.1.0 had been tested with this feature. develop branch (next release 2.2.0) is in progress with several refactoring and our QA team doesn't test the module for now.

Perhaps you should use the module published on PrestaShop addons website witch is more stable and ready to use ? Save cards has been added on version 2.1.0.

Clotaire for 202

**Comment by crashncrow** [comment]
Hi Clotaire, thanks for the super fast response

I already tried version 2.1.0 but it generates too many payment intents in high traffic environments.

Diego

**Comment by 202-ecommerce** [comment]
Ok I understand. In fact version 2.2 will include this refactoring of intents generation.

@mribeiro202 test for me with best résulte of this feature.
For private exchange help and support could you please send us a message on Prestashop addons web site 
https://addons.prestashop.com/en/payment-card-wallet/24922-stripe-official-sca-ready.html#seller

Have a nice day
Clotaire
