### ISSUE TITLE
Can't see card input, but I see massive logos!

### ISSUE THREAD

**Issue by Fabio-Paccosi** [202-ecommerce/stripe_official#25]
Dear community,

I have a problem with my stripe v2.1.0 module on Prestashop v1.7.6.4 and PHP 7.3.18.
When I go to card options for payment, I see this and I can't go forward: 

<img width="771" alt="Schermata 2020-07-02 alle 09 20 43" src="https://user-images.githubusercontent.com/59596946/86329116-0375b600-bc46-11ea-9b79-aeda55fe43e4.png">
<img width="771" alt="Schermata 2020-07-02 alle 09 20 54" src="https://user-images.githubusercontent.com/59596946/86329119-040e4c80-bc46-11ea-91a9-7afc51cb88f5.png">

I think it's a resource loading problem, as stripe is configured correctly and this seems to be a fairly common problem.
Can you help me? Thanks in advance

**Comment by clotaire202** [comment]
Hi @Fabio-Paccosi 

We can help you on this subject but you have to contact the support service through this link :
https://addons.prestashop.com/en/payment-card-wallet/24922-stripe-official-sca-ready.html#seller

Have a nice day

**Comment by Fabio-Paccosi** [comment]
Thank you, I've contact the support.
