### ISSUE TITLE
Display of card icons in multistore environment

### ISSUE THREAD

**Issue by lmeyer1** [202-ecommerce/stripe_official#33]
There is a bug with the display of the card icons in multistore environment

## How to reproduce:
- I have a Prestashop installation with multistore enabled.
- I installed stripe in more than one store.
- I checked in the options of the Stripe module *Display the long version of the form with the card logos instead of the condensed version.*

## Expected behavior:
On the payment form of each store are displayed the icons of the current store

## Actual behavior:
All the icons of all the stores display everywhere.

Example configuration:
- Store 1: enable Mastercard, Visa and Amex
- Store 2: enable CB, Mastercard and Visa
Result: in both stores is displayed the following 1 CB icon, 2 Mastercard icons, 2 Visa icons and 1 Amex icons

**Comment by clotaire202** [comment]
Thank you for your report. We will try to reproduce and fix the bug in the next minor version.

**Comment by lmeyer1** [comment]
Thanks for your answer. I think I found it. I'll test Monday and open a pull request.

**Comment by mribeiro202** [comment]
Hello @lmeyer1 

Thank you again for you help we are working on your PR https://github.com/202-ecommerce/stripe_official/pull/34 
Have a nice day

**Comment by mribeiro202** [comment]
Hi @lmeyer1 

The latest version of Stripe (v2.3.2) is now available, since this afternoon. 
Have a nice day.
