### ISSUE TITLE
"Buy products" button not clickable.

### ISSUE THREAD

**Issue by sandor111** [202-ecommerce/stripe_official#35]
Hi I have now received multiple messages from my customers that the buy products button is not useable in some cases such as in this screenshot a customer send to me:
![image](https://user-images.githubusercontent.com/17690323/96105432-5106ed80-0eda-11eb-81bd-875c0acd7da9.png)

**Comment by fpanico82** [comment]
Hi, for this problem I recommend contacting the module assistance service: https://addons.prestashop.com/it/contact-us?id_product=24922

Thank you.

**Comment by sandor111** [comment]
Okay thanks!
