### ISSUE TITLE
Feature : Allow an option to override the Stripe Descriptor 

### ISSUE THREAD

**Issue by Raphy** [202-ecommerce/stripe_official#36]
Hello,

I'd like to suggest a great feature for this Prestashop module.

I own multiple shops and I'd like to have a custom statement for each shop instead of the default one configured on my Stripe account.
For example, my company's name is `Raphy Shops` and the default statement descriptor is `RAPHY SHOPS` and the shortened descriptor is `RS`.
I own 2 shops : `Awesome Shop` and `Dess Me`. I'd like to set the descriptors `AWESOME SHOP` / `AS` and `DRESS ME` / `DM` for these shops :)

In the module configuration we can add a checkbox `Override default statements` and allow to override the statement descriptor and the shortened one.

I've never developed Prestashop modules but if I can, I will suggest à PR ;)

**Comment by mribeiro202** [comment]
Hello,

Thank you for your idea of evolution, we appreciate all ideas that can help merchants.
We will study your suggestion to see if we can realise it, we will inform you once we have made a decision on it.

Have a nice day.

Michael for 202

**Comment by benoittravers** [comment]
Hi,

Has there been any progress on this piece? It would be very useful.

Thanks

**Comment by clotairer** [comment]
Unfortunately, This feature is not yet register in the road map. We will submit again this idea on the product team.

**Comment by benoittravers** [comment]
Thanks

**Comment by 202-ecommerce** [comment]
After years of hard work with Stripe connector for PrestaShop, 202 ecommerce will stop supporting Stripe module on January 9th 2023.
After this date, merchants will get [support directly](https://support.stripe.com/contact/email?topic=third_party_integrationshttps://support.stripe.com/contact/email?question=other&topic=third_party_integrations&subject=Prestashop%20Support%20Request&body=Include%20details%20of%20your%20Prestashop%20issue:%20)
