### ISSUE TITLE
Problem on payment

### ISSUE THREAD

**Issue by bibidinu** [202-ecommerce/stripe_official#37]
Invalid Stripe API version: 2020-03-02;alipay_beta=v1. You do not have permission to pass this beta header: alipay_beta. If you have any questions, we can help at https://support.stripe.com/.

I updated both the module and the api to the latest version but the payment problem continues to persist.

Version module 2.2.2 
Prestashop 1.7.6.8

**Comment by benrich** [comment]
I'm too wondering why this alipay_beta API version is being used.  For context

./views/js/payments.js

`{ betas: ["alipay_pm_beta_1"], apiVersion: "2020-03-02;alipay_beta=v1", }`

Not that changing core files is a good idea but changing the version to this at least works (for me)

`{  apiVersion: "2020-08-27", }`

Obviously needs looking into properly

**Comment by bibidinu** [comment]
Thanks Ben i have change the code and now work fine.
Thanks

**Comment by mribeiro202** [comment]
Hello, thank you for warning us.
We made a patch on version 2.2.3 which is waiting for validation by the PrestaShop team.
