### ISSUE TITLE
Module doesn't work behind HTTP/HTTPS Proxy

### ISSUE THREAD

**Issue by DarkOwracle** [202-ecommerce/stripe_official#40]
Stripe Module doesn't work behind a HTTP Proxy, the problem come from the cURL. I can't configure the stripe keys because cURL doesn't take environnement variables.

Stripe ne marche pas derrière un Proxy HTTP, je sais que le problème vient de cURL. Je ne peux pas valider les clés stripe car cURL ne prend pas l'option Proxy.

**Comment by sandor111** [comment]
Could you send the error it gives?
