### ISSUE TITLE
composer.json is not compatible with Prestashop specs, thus stripe_official cannot be required in Prestashop

### ISSUE THREAD

**Issue by lmeyer1** [202-ecommerce/stripe_official#44]
Prestashop 1.7 makes heavy usage of composer. Many modules can be installed with composer adding them to PrestaShop's composer.json.

In order for this to work, the module's composer.json must adhere to some rules ([see Prestashop doc](https://devdocs.prestashop.com/1.7/modules/concepts/composer/)). Especially, `"type": "prestashop-module"` is required (and more general fields like `name`, `description`, `homepage` and `authors`.

I can prepare a pull request that allows then to include `stript_official` in a Prestashop install with composer. by adding this to to Prestashop's composer.json:

    "require": {
        "202-ecommerce/stripe_official": "dev-master#<commit>",
        ( ... Prestashop's requirements ... )
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "git@gitlab.com:202-ecommerce/stripe-official.git"
        },
        ( ... Prestashop's custom repositories ... )

 I dont' know what other steps would be required to allow simple `composer require 202-ecommerce/stripe_official`.

Are you interested in this pull request? Or do you think the use cases would be too small? (I'm using it for our custom deployments of Prestashop).

**Comment by mribeiro202** [comment]
Hello @lmeyer1 

Thank you for your help, we are always happy to receive PR.

**Comment by mribeiro202** [comment]
Hi @lmeyer1 

I'm closing this issue, but if you want to do the PR don't hesitate
