### ISSUE TITLE
In multishop setup, $stripeDispute->orderHasDispute connects to the wrong stripe account

### ISSUE THREAD

**Issue by lmeyer1** [202-ecommerce/stripe_official#45]
## Prestashop setup
- Setup prestashop in multishop node
- Configure shop 1 with stripe account 1
- Configure shop 2 with stripe account 2

## Action that leads to error
- Connect to Prestshop BO
- Select *All shops*
- Search for an order of shop 2
- Display that order
- => The information in the payment detail will not show the disputes on the payment.

## Explanation
In the function `orderHasDispute` (`classes/StripeDispute.php, line 51), `$disputes = $this->getAllDisputes();` should get the disputes of the stripe account connected to the shop of the current order, but, since no shop is selected, it will connect to the stripe account of shop 1 (Prestashop always loads the configuration of shop 1 if no shop is selected).

**Comment by mribeiro202** [comment]
Hello @lmeyer1 

We are working on your PR, thank you for you help.
https://github.com/202-ecommerce/stripe_official/pull/43

**Comment by mribeiro202** [comment]
Hi @lmeyer1 

I close this ticket because you made the PR.

Thank you and have a nice day
