### ISSUE TITLE
The Stripe module not visible in the module manager nor on the addons.prestashop.com

### ISSUE THREAD

**Issue by staniek** [202-ecommerce/stripe_official#50]
Thanks for the great module.

A visibility issue:
The addon page exists but https://addons.prestashop.com/en/payment-card-wallet/24922-stripe-official-sca-ready.html is not possible to find on addons.prestashop.com by e.g. using the Search. I am not sure it's expected especially that Stripe is a partner to Prestashop. In particual I am unsure this can be the cause for the next issue as explained below. 

More importantly in the Prestashop backoffice (1.7.7.2) the module is not listed in the module manager. The only way to access the configuration page is to visit the URL ..../index.php?controller=AdminModules&configure=stripe_official directly. Anyway, updating, uninstalling or disabling the module is not possible.

Attaching a screenshot for my all pretty standard payment modules. 
![Screenshot_20210325_150012](https://user-images.githubusercontent.com/7920289/112485922-b1e4fc80-8d7b-11eb-869d-9a508c187d8a.jpg)

Furthermore, the Design->Positions page lists the module hooks just fine; here's an excerpt:
![Screenshot_20210325_150711](https://user-images.githubusercontent.com/7920289/112486103-dfca4100-8d7b-11eb-8b37-b8b505a597ab.jpg)

That said, the stripe integration works for card payments, not for Digital Wallets like Google Pay (they're enabled in the config).

Best regards
Jarek

**Comment by mribeiro202** [comment]
Hello @staniek 

Thank you for your issue and for your nice comment.
We have changed some settings in our PrestaShop account and now you should be able to access the Stripe module from the back office.

Have a nice day !

**Comment by staniek** [comment]
Confirmed, works great, thanks.
