### ISSUE TITLE
Encountered some incorrect charges

### ISSUE THREAD

**Issue by kenlog** [202-ecommerce/stripe_official#52]
Hi guys, I have encountered some incorrect charges, specifically in one case greater than the order amount and in another case lower. The version of the module used 2.3.1 instead PS v1.7.7.1
If you provide me with information on how to proceed to identify the cause of the bug we could investigate further.
Thanks

**Comment by mribeiro202** [comment]
Hello @kenlog 
We would need more information to reproduce your problem, I suggest you contact the support department directly so they can reproduce and identify the problem. 
Here is the link: https://addons.prestashop.com/en/contact-us?id_product=24922

**Comment by kenlog** [comment]
@mribeiro202 thank you very much i contacted by addons.
