### ISSUE TITLE
SOFORT Payments are stuck in "waiting for payment" state in Prestashop

### ISSUE THREAD

**Issue by icemansparks** [202-ecommerce/stripe_official#54]
For quite some time now,  the orders that are done with the module where customers used "SOFORT" as the payment option, seem to be stuck in the "payment pending / waiting for payment" state even if the payment is already received and displayed in the stripe backend.

**Comment by mribeiro202** [comment]
Hello @icemansparks 
I think you should write to our support team and they will help you to analyse this problem.
Here is the link: https://addons.prestashop.com/en/contact-us?id_product=24922

**Comment by mribeiro202** [comment]
Hi @icemansparks 

The latest version of Stripe (v2.3.2) is now available, since this afternoon. Maybe you could try to update the module to see if it can fix your problem.

Have a nice day.
