### ISSUE TITLE
Partial refund problem

### ISSUE THREAD

**Issue by bibidinu** [202-ecommerce/stripe_official#55]
Every time I issue a partial refund, I mark the order as canceled and send the email to the customer as canceled. How can I solve the problem?

**Comment by mribeiro202** [comment]
Hello @bibidinu 

Where do you make the refund from? Stripe Dashboard or PrestaShop Back Office ?

**Comment by bibidinu** [comment]
Prestashop Back Office from module Stripe

**Comment by mribeiro202** [comment]
We are currently reworking the refund functionality of our module as we are aware of some malfunctions. When our refund patch version is released I will let you know. Have you tried using the functionality within the Stripe Dashboard?

**Comment by mribeiro202** [comment]
Hi @bibidinu ,

We made a fix on the next release for your issue.
This is not actually available but i will tell you when the new version will be on addons.

Have a nice day

**Comment by andromaque** [comment]
Hello,

has this bug been resolved? 

Whereas the partial refund is made through the Stripe dashboard or the module, the order status is changed to "cancelled", which is very annoying because then we have to deal with the customer stressed out thinking that it's order has been cancelled.

Thank you.

**Comment by devonto** [comment]
Hello, I have a client facing the same issue in 2.4.4.
The hack has been applied, however can it be assured that it will be resolved in the 2.4.5 milestone that was planned since 5th May?

**Comment by clotairer** [comment]
A pull request is now available #159 

With this PR, a partial refund from Stripe Dashboard will not canceled the order.

**Comment by clotairer** [comment]
Fixed by #165

**Comment by clotairer** [comment]
[2.4.5-RC1](https://github.com/202-ecommerce/stripe_official/releases/tag/2.4.5-RC1) released here and can be downloaded to test.

Thank you.
