### ISSUE TITLE
Is the newest Stripe API version supported?

### ISSUE THREAD

**Issue by JaqubR** [202-ecommerce/stripe_official#57]

**Comment by mribeiro202** [comment]
Hello @JaqubR 

Do you have a problem with the new Stripe API? If so what is the problem?

**Comment by JaqubR** [comment]
Hey @mribeiro202 thanks for replying, I was just wondering if I can safely upgrade to the newer API version - I'm currently on 2019-02-03, and I'd like to upgrade to 2020-08-27.

**Comment by mribeiro202** [comment]
@JaqubR 

For our developments we always use the latest version of the API so you can use the latest version.

**Comment by JaqubR** [comment]
Alright thanks!
