### ISSUE TITLE
Order is not created, payment is received

### ISSUE THREAD

**Issue by JaqubR** [202-ecommerce/stripe_official#58]
Sometimes when a customer places and order I receive the payment, but the order in prestashop is not created. Customer receives error message that there was an error during payment, as if the payment was rejected. In the prestashop logs I found the following: `Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart `

**Comment by mribeiro202** [comment]
Hello @JaqubR ,

Can you tell me more about your environment?
What version of the module are you using?

**Comment by JaqubR** [comment]
> Hello @JaqubR ,
> 
> 
> 
> Can you tell me more about your environment?
> 
> What version of the module are you using?

I'm using the newest version of the module - 3.2.1, my prestashop is on 1.7.4.4

**Comment by Mindfield-Studio** [comment]
Hi, got the same issue here with the same versions... and if the customer makes another cart just after, the paiement is accepted without doing the full checkout (probably due to the cookie used to link the cart and the order).
For now, it happens on Bancontact paiements.

**Comment by mribeiro202** [comment]
Hello @JaqubR and @Mindfield-Studio 
we have made a fix for this kind of problem on the next version 2.3.2 which should be available very soon.
I will let you know when it is available on addons.

Have a nice day

**Comment by mribeiro202** [comment]
Hi @Mindfield-Studio and @JaqubR 

The latest version of Stripe (v2.3.2) is now available, since this afternoon. Maybe you could try to update the module to see if it can fix your problem.

Have a nice day.

**Comment by thomasmediaa** [comment]
Hi!
I encounter the same problem since I updated the module from v2.3.2 to v2.3.4 (Prestashop 1.7.7.2)

**Comment by mribeiro202** [comment]
Hi everyone,

I take the liberty of closing this issue, do not hesitate to reopen if necessary.
You can install the version 2.3.6 available on PS addons just here ==> https://addons.prestashop.com/en/payment-card-wallet/24922-stripe-official-sca-ready.html

Have a nice day
