### ISSUE TITLE
Error on Module Installment

### ISSUE THREAD

**Issue by paulcruz03** [202-ecommerce/stripe_official#59]
![image](https://user-images.githubusercontent.com/30888544/117304712-9e679e00-aeb0-11eb-9ffb-83c6a7cf73f1.png)

Hi, I encounter this error whenever I install the module. I hope the image can provide more information about this.

MySQL version: 8.0.23
MySQL engine: InnoDB
PHP version: 7.2.34
PrestaShop version: 1.7.7.2

**Comment by mribeiro202** [comment]
Hello @paulcruz03 
I think you should write to our support team and they will help you to analyse this problem.
Here is the link: https://addons.prestashop.com/en/contact-us?id_product=24922

Do you tried without debug mode ?

**Comment by paulcruz03** [comment]
It worked without debug mode. Thanks!
