### ISSUE TITLE
Massive image

### ISSUE THREAD

**Issue by WebbieFrank** [202-ecommerce/stripe_official#6]
Hi,
I use the Stripe addon, and I have noticed that, when I go to my shopping cart, the Visa/Mastercard logo turns out gigantic (over half a webpage, too big for a screenshot).
Also, in its folder within the modules, the image is 100x324 in size.
Could you look into that, please?
Thanks.

**Comment by WebbieFrank** [comment]
I also need to point out you can't select the card details. However, on a mobile device, everything works as it should, Please find attached a screenshot.
![2020-02-28 15 02 21 www accordeonmuziek tk 14011b74cb56](https://user-images.githubusercontent.com/38144377/75564471-226bfd80-5a44-11ea-9883-79ff75c84dc4.jpg)

**Comment by clotaire202** [comment]
Hi,

Thank you for your issue.
This bug was fixed in release 2.0.8 (publish 10 december 2019). Please update your module.
If you already have a problem, please contact our support team here https://addons.prestashop.com/contact-form.php?id_product=24922

Regards,
202 Team
