### ISSUE TITLE
tracking is broken

### ISSUE THREAD

**Issue by Dh42** [202-ecommerce/stripe_official#60]
This has been broken for a couple of months. https://github.com/202-ecommerce/stripe_official/blob/f603061b4e7511d59c04c5be0107dd24c7ab859b/views/templates/admin/_partials/configuration.tpl#L31

https://www.prestashop.com/forums/topic/1046676-error-in-connecting-account-with-stripe-platform/

**Comment by mribeiro202** [comment]
Hello @Dh42 
I think you should write to our support team and they will help you to analyse your problem.
Here is the link: https://addons.prestashop.com/en/contact-us?id_product=24922

Have a nice day

**Comment by Dh42** [comment]
I don't need help, I am reporting an easily reproduce-able issue about your module being broken.

**Comment by mribeiro202** [comment]
Hello,

If you are talking about the problem of connection between the Stripe account and the module using the "Connect with Stripe" button, it was a problem coming directly from PrestaShop and not from our module as we told several merchants who contacted us about it.
We were therefore dependent on PrestaShop to fix the problem on their side, which was done last week. From now on you can use the login button to connect your Stripe account.

Have a nice day.

Translated with www.DeepL.com/Translator (free version)

![Capture d’écran 2021-06-14 à 16 08 49](https://user-images.githubusercontent.com/65406895/121905901-e210bb80-cd2a-11eb-8de8-3685014555e5.png)

**Comment by Dh42** [comment]
We both know it could have been fixed in the module. By waiting on them to fix it, you have effectively left the module not working on several versions of prestashop. With development practices like this and we ask ourselves why people are fleeing the platform.
