### ISSUE TITLE
PS 1.6.1.5 - Stripe 2.3.1 problems

### ISSUE THREAD

**Issue by HartLarsson** [202-ecommerce/stripe_official#61]
Seems the module is not compatible with 1.6.1.x.

In errorlog_php i've many errors like:

`[10-May-2021 10:17:58 Europe/Rome] PHP Fatal error:  Uncaught exception 'Stripe\Exception\InvalidArgumentException' with message 'api_key cannot contain whitespace' in /home/www/public_html/modules/stripe_official/vendor/stripe/stripe-php/lib/BaseStripeClient.php:227
Stack trace:
#0 /home/www/public_html/modules/stripe_official/vendor/stripe/stripe-php/lib/BaseStripeClient.php(59): Stripe\BaseStripeClient->validateConfig(Array)
#1 /home/www/public_html/modules/stripe_official/classes/StripeDispute.php(44): Stripe\BaseStripeClient->__construct('\t sk_live_b3BTw...')
#2 /home/www/public_html/modules/stripe_official/classes/StripeDispute.php(51): StripeDispute->getAllDisputes()
#3 /home/www/public_html/modules/stripe_official/stripe_official.php(1359): StripeDispute->orderHasDispute(NULL)
#4 /home/www/public_html/classes/Hook.php(587): Stripe_official->hookDisplayAdminOrderContentOrder(Array)
#5 /home/www/public_html/classes/Hook.php(542): HookCore::coreCallHook(Object(Stripe_official), 'hookdisplayAdmi...', Array)
#6 /home/xyz in /home/www/public_html/modules/stripe_official/vendor/stripe/stripe-php/lib/BaseStripeClient.php on line 227`

this error is created when in BO you can try to edit an order.

Plus if you try to configure the module there are many JS errors that not allow to see the interface:

![image](https://user-images.githubusercontent.com/16102074/117650018-7fa72700-b190-11eb-9b0c-57eae9a76219.png)

We run on php 5.6 version but even switching to 7.0 there is the same problem

**Comment by mribeiro202** [comment]
Hello @HartLarsson 
I think you should write to our support team and they will help you to analyse this problem.
Here is the link: https://addons.prestashop.com/en/contact-us?id_product=24922

**Comment by mribeiro202** [comment]
Hi @HartLarsson 

The latest version of Stripe (v2.3.2) is now available, since this afternoon. Maybe you could try to update the module to see if it can fix your problem.

Have a nice day.

**Comment by mribeiro202** [comment]
Hi @HartLarsson 

I take the liberty of closing this issue, do not hesitate to reopen if necessary.

Have a nice day
