### ISSUE TITLE
Google Pay

### ISSUE THREAD

**Issue by NadhemMohamedRached** [202-ecommerce/stripe_official#66]
button google  pay not showing on Aandroid devices

**Comment by mribeiro202** [comment]
Hello @NadhemMohamedRached ,

Can you tell me a little more about the problem so that I can reproduce:
What is your version of PrestaShop?
What is your version of the Stripe module?
What device do you use?

Thank you.

**Comment by NadhemMohamedRached** [comment]
Prestashop 1.7.6.3
stripe 2.3.1 
i tested this on multiple devices huawei p30 pro et p30 lite et xiaomi 
the button googlePay not working when i use mobile (on desktop work fine ) but on mobile i have this message 

Unable to download payment manifest "https://pay.google.com/gp/p/payment_method_manifest.json".
commande:1 Unable to download payment manifest "https://pay.google.com/gp/p/payment_method_manifest.json".
commande:1 Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 10

**Comment by mribeiro202** [comment]
Thank you @NadhemMohamedRached .

With all this information we will be able to reproduce and correct this.
Once this is done I will let you know.

Have a nice day.

**Comment by NadhemMohamedRached** [comment]
thanks @mribeiro202

**Comment by mribeiro202** [comment]
Hi @NadhemMohamedRached 

Is your problem solved with the latest version 2.3.6 of the module?

have a nice day
