### ISSUE TITLE
Can't change payment method (from bancontact to card)

### ISSUE THREAD

**Issue by zorrobiwan** [202-ecommerce/stripe_official#67]
PS : 1.6.1.7
Stripe module :  2.3.1

Error received:

> "The provided PaymentMethod has failed authentication. You can provide payment_method_data or a new PaymentMethod to attempt to fulfill this PaymentIntent again."

How to reproduce:
- Payment initiated with bancontact (belgian payment mean) then cancelled during the payment
- go back to the payment page and chose credit card
- fill the card information then pay
=> error received

In the logs, payment_method_types is still "bancontact" despite the fact that card has been chosen afterward:

>       "payment_method_types": [
>         "bancontact"
>       ],

> "expected_payment_method_type": "card",

More logs are available if needed.
Btw, same payment is used even bancontact try has been cancelled and I can't see any try to update the payment method in the payment initiated which is still noted as "bancontact"

![image](https://user-images.githubusercontent.com/2226019/122196454-8b74c000-ce97-11eb-9a89-f2192451cb98.png)

Thanks

**Comment by mribeiro202** [comment]
Hi @zorrobiwan ,

First of all thank you for your issue, we have fixed this on the next version of the module 2.3.2, we are doing some final test and other fix before to release it on addons.

I can ping you here when this version is available.

**Comment by zorrobiwan** [comment]
Amazing! Thanks for the quick answer.
I won't be so far and will be ready to test the module on our customer shop once released.
Thanks again

**Comment by mribeiro202** [comment]
Hi @zorrobiwan  

The latest version of Stripe (v2.3.2) is now available, since this afternoon. 

Have a nice day.

**Comment by zorrobiwan** [comment]
Test seems to be ok. I can try with bancontact, cancel it and order with a credit card. Thx
