### ISSUE TITLE
Webhook not created automatically

### ISSUE THREAD

**Issue by maximedewelle** [202-ecommerce/stripe_official#69]
Hi,

I've installed the module on my prestashop website. I've also connected the module to Stripe.
Payments are processed successfully but the webhook is not configured in my Stripe account and the status of some intend payments are not updated.
I have no idea of the URL of the endpoint that I should create as it is specified in the documentation that the webhook should be created automatically.

Thank you for your help.

**Comment by mribeiro202** [comment]
Hello @maximedewelle 
I think you should write to our support team and they will help you to analyse this problem.
Here is the link: https://addons.prestashop.com/en/contact-us?id_product=24922

**Comment by mribeiro202** [comment]
Hi @maximedewelle 
The latest version of Stripe (v2.3.2) is now available, since this afternoon. Maybe you could try to update the module to see if it can fix your problem.

Have a nice day.

**Comment by mribeiro202** [comment]
Hi @maximedewelle 

I take the liberty of closing this issue, do not hesitate to reopen if necessary.

have a nice day
