### ISSUE TITLE
Enable P24 payments

### ISSUE THREAD

**Issue by JaqubR** [202-ecommerce/stripe_official#7]

**Comment by clotaire202** [comment]
Hi,we added your suggestion on the product backlog

**Comment by clotaire202** [comment]
Hi,

Your issue is schedule to be develop on release 2.2.0. Expected delivery June / July.
You can follow issue #14 

Please contact our support team on [PrestaShop addons ](https://addons.prestashop.com/en/contact-us?id_product=24922) if you want to participate to our beta tests.

Thank you.
