### ISSUE TITLE
hookDisplayOrderConfirmation not called

### ISSUE THREAD

**Issue by Kixell-NicolasJardillier** [202-ecommerce/stripe_official#73]
Dear Support, after a payment the hook DisplayOrderConfirmation is not called.
Test on Prestashop 1.7.7.4 installed from scratch and test mode for Stripe.

This is a big issue as several modules need this hook to dispatch pixels and/or trigger somme conversion data.
Best regards

**Comment by mribeiro202** [comment]
Hi @Kixell-NicolasJardillier,

Can you tell me which version of module you use ?

**Comment by rjtubera** [comment]
Hi I'm also having the same issue, using the version 2.3.4

**Comment by Chrisi1321** [comment]
Same issue. However the hook is called on the main shop but not on my other multishops with seperate stripe accounts

**Comment by Kixell-NicolasJardillier** [comment]
> Hi @Kixell-NicolasJardillier,
> 
> Can you tell me which version of module you use ?

It was on the last version when I wrote this issue

**Comment by otherprod** [comment]
Bonjour, nous avons le même problème avec cette dernière version du module, ce qui est trrès problématique puisque l'ensemble des modules de conversion, de stats se basent sur ce hook que vous n'utilisez plus et une boutique sans ses infos critiques. 

Si vous avez le problème du timetout avec les ios 14 nous avons trouvé une solution qui consiste à ca ligne 587: 

`
$.ajax({
            type: 'POST',
            dataType: 'json',  
            async: true, //ICI 
            timeout: 300000, //LA
            url: stripe_validation_return_url,
            data: {
                response: response,
                saveCard: saveCard
            },
            success: function(datas) {
                if (datas['code'] == 0 || datas['code'] == 1) {
                  window.location.replace(datas['url']);
                }
            },
            error: function(err) {
                console.log(err);
            }
        });
`

**Comment by mribeiro202** [comment]
HI everyone,

Thank you for your issue, we are currently working on it.
I will let you know once we made a release with this fix.

Have a nice day.

**Comment by clotairer** [comment]
We publish the fix on release 2.4.0

You can update your addon. If you have any trouble do not hesitate to contact our technical support here : https://addons.prestashop.com/en/contact-us?id_product=24922
