### ISSUE TITLE
Webhook "conflict" with another payment mode

### ISSUE THREAD

**Issue by Mindfield-Studio** [202-ecommerce/stripe_official#78]
Hi,

This morning I had a strange behavior:

- A customer tried to pay with Stripe, his card was declined by Stripe
- Few seconds later, he paid with Paypal (module from 202) and succeed
- Stripe sent a webhook just after and order status changed to "Payment Error"

Does webhook check transaction ID or another related thing ? 

Thank you ! 

EDIT: Prestashop 1.7.4 and Stripe Module 2.3.5

**Comment by Mindfield-Studio** [comment]
Thank you ;)

**Comment by Mindfield-Studio** [comment]
After looking in the code, it seems it does not really fix the issue in every cases (even if the test is usefull):
I think the main issue is the HTTP 400 error response when Stripe send the payment error to the webhook. I guess that if you use another card (a valid one) after a payment error, you can have a "Payment Error" anyway (same module, different card).

**Comment by Mindfield-Studio** [comment]
After some investigations, I think I found the bug. In 2.3.5, each action on Stripe is done twice, in "sync" mode (without the webhook), then in "async" mode (with the webhook). As far, it looks good, but:
- if you change the order state before the webhook call: the order state come back to the webhook related state (easy to reproduce, by changing order state before hook call)
- if 3DSecure failed: the webhook response is a HTTP 400 (probably because order is not yet created, the error was previously handled is "sync" mode)
- if payment failed: the behavior looks like the 3DSecure one, but Stripe do retries because of the HTTP 400 error. If an order is created with another paiement method, the webhook will respond with a HTTP 200 and will change state to "Payment Error" (bug, payment method/card changed).

I will work today on a fix, and I will post it here :)

**Comment by Mindfield-Studio** [comment]
For some HTTP 400 errors, in "ValidateOrderActions::chargeWebhook" :

```
$id_order = Order::getOrderByCartId($id_cart);
if ($id_order == false) {
    if ($this->conveyor['event_json']->type == 'payment_intent.requires_action') { // 3DSecure errors
        ProcessLoggerHandler::logInfo(
            'Cart #' . $id_cart . ' requires action to process',
            null,
            null,
            'webhook'
        );
        ProcessLoggerHandler::closeLogger();
        http_response_code(200);
        return true;
    } else if ($this->conveyor['event_json']->type == 'charge.refunded') { // Refunded (without order)
                ProcessLoggerHandler::logInfo(
                    'Cart #' . $id_cart . ' has been refunded',
                    null,
                    null,
                    'webhook'
                );
                ProcessLoggerHandler::closeLogger();
                http_response_code(200);
                return true;
    }  else if ($this->conveyor['event_json']->type == 'charge.failed') { // Charge failed (without order)
        ProcessLoggerHandler::logInfo(
            'Cart #' . $id_cart . ' charge failed',
            null,
            null,
            'webhook'
        );
        ProcessLoggerHandler::closeLogger();
        http_response_code(200);
        return true;
    } else {
        ProcessLoggerHandler::logError(
            '$id_order = false',
            null,
            null,
            'webhook'
        );
        ProcessLoggerHandler::closeLogger();
        http_response_code(400);
        return false;
    }
}
```

**Comment by Mindfield-Studio** [comment]
> For some HTTP 400 errors, in "ValidateOrderActions::chargeWebhook" :
> 
> ```
> $id_order = Order::getOrderByCartId($id_cart);
> if ($id_order == false) {
>     if ($this->conveyor['event_json']->type == 'payment_intent.requires_action') { // 3DSecure errors
>         ProcessLoggerHandler::logInfo(
>             'Unknown order requires action to process',
>             null,
>             null,
>             'webhook'
>         );
>         ProcessLoggerHandler::closeLogger();
>         http_response_code(200);
>         return true;
>     } else if ($this->conveyor['event_json']->type == 'charge.refunded') { // Refunded (without order)
>                 ProcessLoggerHandler::logInfo(
>                     'Unknown order has been refunded',
>                     null,
>                     null,
>                     'webhook'
>                 );
>                 ProcessLoggerHandler::closeLogger();
>                 http_response_code(200);
>                 return true;
>     }  else if ($this->conveyor['event_json']->type == 'charge.failed') { // Charge failed (without order)
>         ProcessLoggerHandler::logInfo(
>             'Unknown order charge failed',
>             null,
>             null,
>             'webhook'
>         );
>         ProcessLoggerHandler::closeLogger();
>         http_response_code(200);
>         return true;
>     } else {
>         ProcessLoggerHandler::logError(
>             '$id_order = false',
>             null,
>             null,
>             'webhook'
>         );
>         ProcessLoggerHandler::closeLogger();
>         http_response_code(400);
>         return false;
>     }
> }
> ```

**Comment by clotairer** [comment]
We have not encountered this issue during our test of 2.4.0 release.

Could you please confirm all 400 error case are now manage properly ?

Do not hesitate to suggest a code modification by sending us a Pull Request.
