### ISSUE TITLE
Webhook charge.failed have no logic 

### ISSUE THREAD

**Issue by JimmyBillan** [202-ecommerce/stripe_official#79]
Hello, 
if the charge.failed webhook is called, ValidationOrderAction will set the current state of the order to PS_OS_ERROR (payment fail) even if the command was already in PS_OS_PAYMENT (payment success).

Example : 
A client have payment_intent( 1)  "blocked" by a rule ("Block if :address_zip_check: = 'fail'"). 
So he retry a new payment_intent(2), => success, the order is created with statut (payment success). all is ok.
1h later, the webhook charge.failed from the payment_intent(1) is fired again. Captured by ValidationOrderAction and set the order state do payment failed.

How can we fix that ? Check if the order is not already in success ? The initial charge.failed shouldn't send back a http400 so there is no retry send ?

**Comment by Mindfield-Studio** [comment]
Got a similar issue with HTTP 400 error:
- On "payment_intent.requires_action" (for 3D Secure), I got a HTTP 400, but no retry planned (I don't know if it's a normal behavior)
- On "charge.failed" (insufficient funds), I got a HTTP 400 with retry planned (and so, order is not set to "Payment Error")

Thank you !

**Comment by Mindfield-Studio** [comment]
@JimmyBillan : HTTP 400 error occurs when webhook is unable to find any order related to the cart id. So, the issue is about the error code (400) who force Stripe to retry the webhook call. I did a workaround about this : #78

**Comment by mribeiro202** [comment]
Hi,

Thank you for this issue, we are working on this fix, you will be notified when the release will be published.

Have a nice day.

**Comment by rjtubera** [comment]
Having the same issue, bump

**Comment by clotairer** [comment]
We have not encountered this issue during our test of 2.4.0 release.

Could you please confirm all 400 error case are now manage properly ?
