### ISSUE TITLE
Install error with prestashop 1.7.7.6

### ISSUE THREAD

**Issue by MoveUpwardsDev** [202-ecommerce/stripe_official#81]
While trying to install the stripe plugin on prestashop v1.7.7.6 I got the following error.

**PHP**: 7.2.34-23
**MySQL**: 8.0.26

No database table are created.

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT' at line 1

CREATE TABLE IF NOT EXISTS `ps_stripe_payment` (`id_payment` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, `id_stripe` VARCHAR(255) NOT NULL, `id_payment_intent` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `id_cart` INT(10) SIGNED NOT NULL, `last4` INT(10) SIGNED NOT NULL, `type` VARCHAR(20) NOT NULL, `amount` DECIMAL(10,2) NOT NULL, `refund` DECIMAL(10,2) NOT NULL, `currency` VARCHAR(3) NOT NULL, `result` INT(10) SIGNED NOT NULL, `state` INT(10) SIGNED NOT NULL, `voucher_url` VARCHAR(255) NOT NULL, `voucher_expire` DATETIME NOT NULL, `voucher_validate` DATETIME NOT NULL, `date_add` DATETIME NOT NULL, PRIMARY KEY (`id_payment`)) ENGINE=InnoDB CHARSET=utf8 COLLATE=DEFAULT;`

**Comment by mribeiro202** [comment]
Hi @MoveUpwardsDev ,

Thank you for your issue.

Our support team can help you solve this problem with the database.
I suggest you contact them using this link ==> https://addons.prestashop.com/en/contact-us?id_product=24922

Have a nice day.

**Comment by mribeiro202** [comment]
Hi @MoveUpwardsDev 

Without any news from you I'm closing this issue.
Do not hesitate to contact us again if you need to.

Have a nice day
