### ISSUE TITLE
clean the table ps_stripe_official_processlogger 

### ISSUE THREAD

**Issue by omhabibal** [202-ecommerce/stripe_official#83]
hi 
I have the ps_stripe_official_processlogger table of several megabytes which slows down a client's site then I emptied it without making him lose important or sensitive data it takes more than 500 MB it is really huge due to spam attacks, I do not take care of spam just to lighten and clean the site
cordialy

**Comment by mribeiro202** [comment]
hi @omhabibal,

For your informations by default logs are kept 5 days and then they are removed automatically.
This is something you can configure using both STRIPE_OFFICIAL_EXTLOGS_ERASING_DAYSMAX, STRIPE_OFFICIAL_EXTLOGS_ERASING_DISABLED variables.
Feel free to modify those values in ps_configuration table if you think this makes sense for you.

Have a nice day.

**Comment by mribeiro202** [comment]
Hi @omhabibal 

Without any news from you I'm closing this issue.
Do not hesitate to contact us again if you need to.

Have a nice day
