### ISSUE TITLE
stripe_official payments not visible in prestashop backend 

### ISSUE THREAD

**Issue by pks891618** [202-ecommerce/stripe_official#87]
Prestahsop version: **1.7.6.8**

stripe_official version : **v2.3.7**

Payment made using this module is not visible in the backend of Prestashop. 

Payments are visible in stripe dashbaord

**Comment by mribeiro202** [comment]
Hi @pks891618 ,

Are you sure this is version 2.3.7 and not 2.3.6?
Can you try to clear your PrestaShop cache and do a payment test again?

**Comment by pks891618** [comment]
yes its 2.3.7

**Comment by pks891618** [comment]
ah sorry its 2.3.6,  this is the latest download from preasthop addons

**Comment by pks891618** [comment]
[v2.3.6-stripe_official (1).zip](https://github.com/202-ecommerce/stripe_official/files/7119771/v2.3.6-stripe_official.1.zip)

other thing i also found that after conifmration the cart is also not cleared and also order not appear in prestashop backend. I have also added the correct webhook

**Comment by mribeiro202** [comment]
Hi @pks891618 

Have you contacted our support service?
If not, I encourage you to do so here ==> https://addons.prestashop.com/en/contact-us?id_product=24922
Have you also tried clearing your shop's cache?

Have a nice day

**Comment by pks891618** [comment]
no not contacted, yes  i have cleared cache

**Comment by pks891618** [comment]
yes i am in discussion with support

**Comment by pks891618** [comment]
waiting for support answer, kindly let me know if there is any other issues, already shared admin login details to support

**Comment by pks891618** [comment]
didnt get any reply from Support, already generated support ticket

**Comment by mribeiro202** [comment]
Hi @pks891618 ,

Have you had any news of help from the support?

Have a nice day

**Comment by pks891618** [comment]
no, its more then 1 week but no reply

**Comment by mribeiro202** [comment]
Hi @pks891618 

Was the support able to help?

**Comment by pks891618** [comment]
sorry so far they are not able to help so i purchased paid module
