### ISSUE TITLE
Hooks attached to DisplayOrderConfirmation is not triggered

### ISSUE THREAD

**Issue by rjtubera** [202-ecommerce/stripe_official#89]
Hello, since the order confirmation will not be reachable, where can we attach all the hooks we put on displayOrderConfirmation before? Any alternative?

Thanks

**Comment by Daxtermania** [comment]
I have same problem https://github.com/202-ecommerce/stripe_official/issues/90

**Comment by andreibexa** [comment]
ps_googleanalytics module is using that displayOrderConfirmation hook. Probably that's why Google Analytics doesn't show any order ?

**Comment by mribeiro202** [comment]
Hello everyone,

We know you are facing issues with the order_confirmation page.
We are currently working on a version of the module that will use the native order confirmation page.

I will inform you when the release will be available.

Have a nice day

**Comment by loreactm** [comment]
Same for us, we'd really like to start using the new version of the module but the missing DisplayOrderConfirmation is breaking Analytics and all sorts of integrations. Thank you!

**Comment by rjtubera** [comment]
It broke so many integrations from our side, hoping it will be fixed soon. It's almost a month since I raised the issue

**Comment by dominictayloruk** [comment]
Breaks conversion metrics and tracking in all ads and analytics.

**Comment by clotairer** [comment]
We publish last week the release 2.4.0 witch solve issued about this issue. Stripe use now the default prestashop landing page after the payment and trigger all hook

You can update your addons. If you have any trouble do not hesitate to contact our technical support here : https://addons.prestashop.com/en/contact-us?id_product=24922
