### ISSUE TITLE
Authorize and Capture

### ISSUE THREAD

**Issue by Nimtereas** [202-ecommerce/stripe_official#9]
Hi,

I see you're committing changes regarding the Authorize and Capture functionnality.

Is it "safe" to use the developer branch to use this functionnality now?
If not, do you know when you should publish a stable version?

Many thanks!

**Comment by 202-ecommerce** [comment]
Hi,

It’s not recommended to use develop version on production. We currently test the  module to prevent regression.

Be patient, the next release is schedule for the next few days.

Regards,
202 teams

**Comment by clotaire202** [comment]
Hi,

Your issue is schedule to be develop on release 2.1.0. Expected delivery May.
You can follow issue #12 

Please contact our support team on [PrestaShop addons ](https://addons.prestashop.com/en/contact-us?id_product=24922) if you want to participate to our beta tests.

Thank you.
