### ISSUE TITLE
Redirect to order-confirmation instead stripe confirmation page

### ISSUE THREAD

**Issue by Daxtermania** [202-ecommerce/stripe_official#90]
Once the order is confirmed, the user is redirected here:

```
$url = Context::getContext()->link->getModuleLink(
    'stripe_official',
    'orderSuccess',
    $datas,
    true
);
```
But it should redirect to the native prestashop confirmation page, similar to this:

```
$url = Context::getContext()->link->getPageLink(
    'order-confirmation',
    true,
    null,
    array(
        'id_cart' => (int)$this->context->cart->id,
        'id_module' => (int)$this->module->id,
        'id_order' => (int)$id_order,
        'key' => $secure_key
    )
);
```
Can you repair it?

**Comment by mribeiro202** [comment]
Hi @Daxtermania ,

Thank you for your issue, we are currently working on it. 
I will let you know once we made a release with this fix.
 
Have a nice day.

**Comment by clotairer** [comment]
We publish last week the release 2.4.0 witch solve issued about this issue. Stripe use now the default prestashop landing page after the payment and trigger all hook

You can update your addons. If you have any trouble do not hesitate to contact our technical support here : https://addons.prestashop.com/en/contact-us?id_product=24922
