### ISSUE TITLE
Order confirmation page missing - Analytics don't track orders

### ISSUE THREAD

**Issue by Thread10** [202-ecommerce/stripe_official#91]
Since an update released on july 2021, all orders end on a strange confirmation page, also, oficial ps_analytics module and google ads, can't track confirmed orders, resulting in bad and low optimised campaigns.

**Comment by mribeiro202** [comment]
Hi @Thread10 

This issue has been already raised (#90 ).
Thus i will close the issue, i will inform you when then release with this fix will be available.

Have a nice day.
