### ISSUE TITLE
Payment accepted status updated twice on backordered orders

### ISSUE THREAD

**Issue by ecenturyuk** [202-ecommerce/stripe_official#92]
Hi
After update to v 2.3.6 on Prestashop 1.7.6.5 there seems to be an additional status update by stripe that overrides the automatic 'On backorder (paid)' status, so this happens;

![order-backordered-status](https://user-images.githubusercontent.com/87011426/133460347-bfc4924f-10c7-4ee6-95b7-9e1ad4b3cc48.jpg)

This does not happen if the order is in stock (it just gives one payment accepted status which is correct) and it did not happen before module update

Thanks

**Comment by mribeiro202** [comment]
Hi @ecenturyuk ,

Thank you for your issue, a merchant has contacted our support to report this problem.
We have therefore made a fix to correct this in the next version of the module.
We are currently in the testing phase of the latest version which includes this fix, once this phase is completed we will release the new module.

Have a nice day

**Comment by mribeiro202** [comment]
Hi @ecenturyuk 

We made a fix for this on the next release 2.3.7 (coming soon).
Thank you for your issue and for your help.

Have a nice day

**Comment by clotairer** [comment]
We publish the release 2.3.7 witch solve this issue.

You can update your addons. If you have any trouble do not hesitate to contact our technical support here : https://addons.prestashop.com/en/contact-us?id_product=24922
