### ISSUE TITLE
When an order is split by prestashop only the first of the split is being captured not the full amount.

### ISSUE THREAD

**Issue by Leenwt** [202-ecommerce/stripe_official#94]
When shipping with multiple shipping agents prestashop splits an order after payment confirmation.

The capture request is then sent from prestashop to stripe for the incorrect amount, as it is only requesting the first part of an order.

This is on a standard install, on the standard theme.

![stripe](https://user-images.githubusercontent.com/21257941/133774020-c06afd21-4dc1-44fb-9d9a-afb3d7d17c60.jpg)
![stripe2](https://user-images.githubusercontent.com/21257941/133774328-156fdfce-22af-4142-8aa2-e410a40c40d2.jpg)

**Comment by mribeiro202** [comment]
Hello @Leenwt ,

First of all, thank you for your issue.
We can reproduce it so we are going to work on it to fix it.
I will come back to you when we made the release with the fix.

Have a nice day

**Comment by mribeiro202** [comment]
Hello @Leenwt ,

We made a fix on the last release 2.3.7 (available on addons).
Can you try to download it and tell me if everything is ok now ?

Have a nice day

**Comment by clotairer** [comment]
We publish the fix on release 2.3.7.

You can update your addons. If you have any trouble do not hesitate to contact our technical support here : https://addons.prestashop.com/en/contact-us?id_product=24922
