### ISSUE TITLE
Problem on checkout page if user not authenticated. 

### ISSUE THREAD

**Issue by electricpizzza** [202-ecommerce/stripe_official#95]
While using onepage checkout or trying to checkout as a guest the Stripe Customer class cant find a customer ID so it raise an exception in **getCustomerById** function.
```
          public function getCustomerById($id_customer, $id_account)
          {
              $query = new DbQuery();
              $query->select('*');
              $query->from(static::$definition['table']);
              $query->where('id_customer = ' . pSQL($id_customer) );
              $query->where('id_account = "' . pSQL($id_account) . '"');
              $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->getRow($query->build());
              if ($result == false) {
                  return $this;
              }
      
              $this->hydrate($result);
      
              return $this;
          }
```

And this can be solve by adding quotation marks for the $id_customer

```
    public function getCustomerById($id_customer, $id_account)
    {
        $query = new DbQuery();
        $query->select('*');
        $query->from(static::$definition['table']);
        $query->where('id_customer = "' . pSQL($id_customer) . '"');
        $query->where('id_account = "' . pSQL($id_account) . '"');

        $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->getRow($query->build());
        if ($result == false) {
            return $this;
        }

        $this->hydrate($result);

        return $this;
    }
```

**Comment by mribeiro202** [comment]
Hi @electricpizzza ,

Thank you for your issue, can you give us more information to reproduce this issue ?
Which PrestaShop version do you use ?
Which Stripe module version do you use ?
Is this a systematic problem or does it occur occasionally?

Have a nice day.

**Comment by electricpizzza** [comment]
Hey @mribeiro202,

The problem accrued to me while using a one page checkout module where the user dont have to be authenticated. so the function I mentioned cant find the id_customer
```
 $query->where('id_customer = ' . pSQL($id_customer) );
```
so it send a query like SELECT * FROM table WHERE 'id_customer =  AND 'id_account = "xxx"
which raise an SQL exception

I am using PrestaShop v1.6.1.6 & Strip v2.3.2

Thanks.
