### ISSUE TITLE
Uncaptured payments (payment method now "manual")

### ISSUE THREAD

**Issue by githubjonny** [202-ecommerce/stripe_official#96]
Hi, we are seeing multiple uncaptured payments each day (approx 1 in 20 payments don't go through correctly and end up uncaptured). The customer sees the checkout complete page so is unaware the issue has occurred.

I have spoke to Stripe and they have said that it's due to the payment method changing from automatic to manual.

Anyone else seeing this and can they confirm if the payment method changed at their end (stripe support live chat should be able to confirm it)?

**Comment by clotairer** [comment]
We publish last week the release 2.4.0 witch solve issued about uncaptured payments.

You can update your addons. If you have any trouble do not hesitate to contact our technical support here : https://addons.prestashop.com/en/contact-us?id_product=24922
